### ISSUE TITLE
Configure simulation run duration

### ISSUE THREAD

**Issue by aornugent** [moja-global/FLINT-UI#10]
All FLINT simulations are temporally explicit (i.e. have a time component). Every run needs to be configured with a start and and end date. Vue Material has a simple date picker component, but it'd be especially helpful if we can also summarise the number of simulation years using moment.js or a similar library - I always recommend using standard logic where dates are concerned 😅

https://vuematerial.io/components/datepicker/
https://momentjs.com/docs/#/displaying/difference/

**Comment by shubhamkarande13** [comment]
@waridrox Have not you fixed this issue via #46 ?

**Comment by waridrox** [comment]
Yes, this has been resolved via material-vue date picker component. Though I am not sure if we require moment.js since the date picker component already has the inbuilt login for leap years etc.

**Comment by aornugent** [comment]
> It'd be especially helpful if we can also summarise the number of simulation years.

Awesome @waridrox - did you happen to include this functionality? It'd be nice to have a summary e.g. 'Simulation length = 5.7yrs" displayed to the user.

**Comment by waridrox** [comment]
Oh! then that would probably require some `moment.js` logic...

**Comment by waridrox** [comment]
Closed via #58
