### ISSUE TITLE
Building the landing page.

### ISSUE THREAD

**Issue by chicken-biryani** [moja-global/FLINT-UI#101]
The current page looks like this:

![image](https://user-images.githubusercontent.com/41121520/138823804-5da3be05-816c-4a44-91d4-a6222ba31adc.png)

What are we aiming at:

![image](https://user-images.githubusercontent.com/41121520/138823964-0c76466c-6536-4c1a-97fa-2459ac7aafe0.png)

**Comment by garvitraj** [comment]
Hi @chicken-biryani and @shubhamkarande13 is there any way I can contribute as a UX/UI for this open-source project as I m on a mission to make UI/UX also open source and improvise the project lookout and experience as an open-source contributor for UX/UI domain. If there is any scope for me in this great organization do let me know. It Would be a pleasure for me to work for the same.
Given my short portfolio of past work to verify my expertise in this field:- https://znap.link/garvitraj

**Comment by chicken-biryani** [comment]
Hey,

@garvitraj that's a really great portfolio. Great work.

Currently, we have a person, Vikrant, giving us suggestions on how to develop the UI/UX of the FLINT-UI. So I am not sure if too many inputs at a time would be a good move.

But we are open to comments and suggestions from your end.

Nonetheless, we do have two projects at moja global dealing with front-end currently:
1) FLINT-UI (This project).
2) Community Website.

I believe the community website could use some inputs on UI/UX.

You could join our slack, from the link provided in the organisation's README, and communicate with @HarshCasper (or any of us) on how to contribute to the community website as a UI/UX person on slack.

**Comment by garvitraj** [comment]
@chicken-biryani and @HarshCasper thanx for the consideration will surely give my best input on the community website.
Just do let me know how should I start. 
Should I find the UI/UX bugs and improvise the design and feel of the website.?
Or anything other than that I can go with. Pls do guide me accordingly

**Comment by garvitraj** [comment]
@chicken-biryani can you help me in joining the slack channel as its asking for the custom email address.
and I don't have that mojaglobal and mullion grp extension email how can I proceed

**Comment by chicken-biryani** [comment]
@garvitraj kindly make use of [this link.](https://t.co/tc684LtWj3?amp=1)

**Comment by garvitraj** [comment]
@chicken-biryani thanks for the guiding will start my work from today
I have figured few UI bugs and a few points that can be improved to provide a seamless experience
Will provide the improvement by tomorrow
Thanks again for making me part of this team

**Comment by yashsehgal** [comment]
Hey all, this updates seems to be a group task, if possible can I join you all? :D
I would love to help you with the UI development/updating part.

**Comment by chicken-biryani** [comment]
Hey, @yashsehgal Definitely!
Currently, we are creating the base for the landing page, post which I am sure there will be a bunch of good first issues/beginner-friendly issues you can take up.

**Comment by yashsehgal** [comment]
Oh thanks @chicken-biryani 
Do let me know if you need any help
