### ISSUE TITLE
Remove the Sidebar

### ISSUE THREAD

**Issue by chicken-biryani** [moja-global/FLINT-UI#105]
Currently, we are motivated to restructure the FLINT-UI.
This issue is a piece of the puzzle.

**Todo**: 

**Comment out/Remove the Sidebar from the UI.**

![image](https://user-images.githubusercontent.com/41121520/141460107-5e6e5ce8-0955-4a56-a960-c45f7472333f.png)

**Comment by himanshu007-creator** [comment]
Hi , i would like to work on this issue.

**Comment by chicken-biryani** [comment]
@himanshu007-creator sure go ahead!
