### ISSUE TITLE
Add Moja Global Logo on the Landing Page Navbar

### ISSUE THREAD

**Issue by sohamsshah** [moja-global/FLINT-UI#109]
### Is your feature request related to a problem? Please describe.

Currently, the landing page looks like this:
![image](https://user-images.githubusercontent.com/47717492/141689959-ba96e257-f3e8-41af-87bf-d9c9334f2fb4.png)

We want to replace brand-text in the navbar with `moja-global` logo.

### Describe the solution you'd like.

Add the Logo in the navbar.

### Describe alternatives you've considered

N/A

### Additional context.

Make sure we implement this such that:
- The Logo doesn't break the UI on responsive behavior
- Use static assets like images from the `/assets` folder. 
- Also, to make it accessible by adding corresponding alt text.
- Add `height` and `width` to make it performant.

**Comment by Marob-nod** [comment]
Hi ! I would be happy to work on it !

**Comment by chicken-biryani** [comment]
Hey, @Marob-nod go ahead!

**Comment by Marob-nod** [comment]
I realized I dont't have the good stack for this project :/

**Comment by chicken-biryani** [comment]
@Marob-nod oh alright. Would you be okay if someone else works on it?

**Comment by Sukriti-sood** [comment]
May I go ahead?

**Comment by chicken-biryani** [comment]
Hey @Sukriti-sood definitely!
