### ISSUE TITLE
Configure GitHub actions for CI and E2E testing

### ISSUE THREAD

**Issue by aornugent** [moja-global/FLINT-UI#11]
Now that we've got some basic features down we don't want to lose them (e.g. #3). It'd be nice to have automated end-to-end testing that, at minimum:
1. Builds the `local` containers from the `flint.cloud` sub-module, using the latest FLINT.example image
2. Builds the UI application
3. Confirms the latest endpoints are compatible with the UI application

Any means to further test the UI functionality would also be fantastic (e.g. modifying the default config to alternative values and validating the response).

**Comment by iamrajiv** [comment]
4. Adding GitHub action to visually test the application using Storybook.

**Comment by aornugent** [comment]
Some examples:
https://www.cypress.io/blog/2021/04/06/getting-start-with-cypress-component-testing-vue-2-3/
https://testing-library.com/docs/cypress-testing-library/intro/

**Comment by aornugent** [comment]
Here ae

> 4. Adding GitHub action to visually test the application using Storybook.

Instructions for deploying Storybook on Chromatic look easy: https://storybook.js.org/tutorials/intro-to-storybook/vue/en/deploy/

**Comment by aornugent** [comment]
We have enabled our first action with #39 - this simply builds the `flint.ui` container and does not do any further testing. More to come!
