### ISSUE TITLE
Create `Button` Component

### ISSUE THREAD

**Issue by sohamsshah** [moja-global/FLINT-UI#111]
### Is your feature request related to a problem? Please describe.

As per the new design updates, we want to update our Button Component across the project. 

### Describe the solution you'd like.

We want a new Button Component which is like:
Normal State:
![image](https://user-images.githubusercontent.com/47717492/141691158-0fcc3d3d-4c0e-4af9-99a2-995118e4a7fd.png)

Hover State:
![image](https://user-images.githubusercontent.com/47717492/141691239-94d3bd10-5869-41ad-9d27-3ff5f56263a5.png)

### Describe alternatives you've considered

The new Button shall go in the `flint.ui/src/components/Button/Button.vue` (create the component in this path). Refer `src/stories/Button.vue` component for more insights. Refer above given design for developing the component.

### Additional context.

Make sure the Button Component is:
- With required extensible props (eg. isDisabled, size, color etc.) 
- Proper Hover state and transition effect on hover
- Tested with different props and on different pages.

Feel Free to ask questions or curiosities around its implementation.

**Comment by ZaidKhan144** [comment]
Hey, I would like to do this, could you assign me, please.

**Comment by chicken-biryani** [comment]
@ZaidKhan144 sure go ahead!

**Comment by ZaidKhan144** [comment]
@chicken-biryani When I was trying to set up the `docker-compose.yml` file by the command `docker-compose up`. 

I was running into this error 
`failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c yarn run build]: exit code: 1`

Could you possibly know what this could be?

Please let me know if you need any more information.

**Comment by chicken-biryani** [comment]
cc: @sohamsshah @waridrox @iamrajiv

**Comment by sohamsshah** [comment]
> @chicken-biryani When I was trying to set up the `docker-compose.yml` file by the command `docker-compose up`.
> 
> I was running into this error `failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c yarn run build]: exit code: 1`
> 
> Could you possibly know what this could be?
> 
> Please let me know if you need any more information.

I would say, you can `cd flint.ui` and then 
`yarn
yarn serve` 

This should `localhost:8000`

**Comment by chicken-biryani** [comment]
@ZaidKhan144 I hope that helps. If not feel free to reach out.

**Comment by ZaidKhan144** [comment]
Where would you like to have its styles in the same file?

**Comment by sohamsshah** [comment]
> Would you like to have its styles in the same file?

It would be better if we have [scoped](https://vue-loader.vuejs.org/guide/scoped-css.html) styles for each vue component.

**Comment by ZaidKhan144** [comment]
@sohamsshah Sweet!

**Comment by ZaidKhan144** [comment]
Could you provide me with the styles for the button?

**Comment by chicken-biryani** [comment]
@ZaidKhan144 I am assuming you're okay with Figma.

Make use of this link - https://www.figma.com/file/JXB1KKGWxD2dLR7dx2hqWS/Flint-UI?node-id=3%3A2 
Let us know if it helps.

**Comment by ZaidKhan144** [comment]
@chicken-biryani oh yeah, totally. Thank you!
