### ISSUE TITLE
Create `Date Picker` Component

### ISSUE THREAD

**Issue by sohamsshah** [moja-global/FLINT-UI#112]
### Is your feature request related to a problem? Please describe.

Currently, the date-picker component looks like:
![image](https://user-images.githubusercontent.com/47717492/141691869-91665754-4747-4e45-b8a5-8b0cd49bb3f4.png)

### Describe the solution you'd like.

We are aiming for this component design as per latest design update for flint.ui
![image](https://user-images.githubusercontent.com/47717492/141691844-7107ca91-86e9-40c0-a3fb-987985de5323.png)

### Describe alternatives you've considered

Create this component in the `flint.ui/src/components/`. You can take reference from other components available in the folder. (don't delete any other component files) 

### Additional context.

Make sure that:
- Use Tailwindcss utility classes
- Proper Props and Implementation
- Test the component by seeing the working at different places where this is used

Feel Free to ask questions or curiosities around its implementation.

**Comment by Dangpham0305** [comment]
assign me. I think i can help you

**Comment by chicken-biryani** [comment]
@Dangpham0305 sure go ahead!

**Comment by sohamsshah** [comment]
Hey @Dangpham0305 , any updates on this? If timing is bad for you, maybe I should un-assign you so someone else can take this?

**Comment by yashsehgal** [comment]
Hey @chicken-biryani @sohamsshah I would like to work on this issue. Can you please assign this to me 😄

**Comment by chicken-biryani** [comment]
Yes, @yashsehgal go ahead

**Comment by yashsehgal** [comment]
Hey, Can I add a prop for providing width to the date-picker component. Like

```vue
<date-picker-point inputWidth="small" />
// means width - 30% from the parent container
```
```vue
<date-picker-point inputWidth="medium" />
// means width - 60% from the parent container
```
```vue
<date-picker-point inputWidth="large" />
// means width - 100% from the parent container
```

**Comment by sohamsshah** [comment]
> Hey, Can I add a prop for providing width to the date-picker component. Like
> 
> ```
> <date-picker-point inputWidth="small" />
> // means width - 30% from the parent container
> ```
> 
> ```
> <date-picker-point inputWidth="medium" />
> // means width - 60% from the parent container
> ```
> 
> ```
> <date-picker-point inputWidth="large" />
> // means width - 100% from the parent container
> ```

Yes, this looks good. Will add flexibility for building the diff frontend in future!
