### ISSUE TITLE
Create `Accordion` Component

### ISSUE THREAD

**Issue by sohamsshah** [moja-global/FLINT-UI#113]
### Is your feature request related to a problem? Please describe.

As per new design, Accordion component is included at multiple places. In general, accordion component is a component that has title text, and on clicking the button; it can be expanded where some descriptive text can be seen. Can refer to different design libraries like chakra/bootstrap etc. for its implementation (props, etc.) eg. [see this](https://chakra-ui.com/docs/disclosure/accordion)

### Describe the solution you'd like.

Create Accordion component similar to:
![image](https://user-images.githubusercontent.com/47717492/141692860-953812e4-3403-4d53-9717-682381c2eb56.png)

### Describe alternatives you've considered

Create this new component in `flint.ui/src/components` folder.

### Additional context.

Make sure that:
- Use Tailwindcss utility classes
- Proper Props and Implementation
- Test the component by seeing the working at different places where this is used

Feel Free to ask questions or curiosities around its implementation.

**Comment by Amishakumari544** [comment]
I want to work on this.

**Comment by chicken-biryani** [comment]
@Amishakumari544 sure! Go ahead!

**Comment by sohamsshah** [comment]
Hey @Amishakumari544  , Do you have any progress on this? Please let us know if you need any more insights upon this.

**Comment by Amishakumari544** [comment]
hey @sohamsshah  sorry for the inconvenience my hand got fractured a little bit that's why I haven't updated here anything. I will do it by today only.
