### ISSUE TITLE
Create footer in landing page

### ISSUE THREAD

**Issue by iamrajiv** [moja-global/FLINT-UI#116]
## Description

As of now, we don't have a footer on the landing page. We can take reference from https://moja.global/ site.

![Screenshot 2021-11-20 at 1 27 42 PM](https://user-images.githubusercontent.com/42106787/142719094-255b56e1-520b-4d20-b8d0-5cc357e204e7.jpg)

**Comment by anjali1102** [comment]
hey @iamrajiv Can I work on this issue

**Comment by chicken-biryani** [comment]
@anjali1102 go ahead!

**Comment by anjali1102** [comment]
Hey @iamrajiv can you share repo of https://moja.global/ as I only found community website repo

**Comment by anjali1102** [comment]
I need help  regarding the vue.js code  

src (folder)
    components (folder)
         Footer (folder)
             Footer.vue (file)

But on localhost   it's not showing footer nor any error
vue.js file  https://codeshare.io/YL7jXn

**Comment by anjali1102** [comment]
App.vue
![App_vue](https://user-images.githubusercontent.com/56559378/142768653-9c7855a9-a4ef-4fc3-9568-25d4c116401b.jpg)


main.js file

https://codeshare.io/eVwqbL

**Comment by sohamsshah** [comment]
> I need help regarding the vue.js code
> 
> src (folder) --components (folder) ----Footer (folder) ------Footer.vue (file)
> 
> But on localhost it's not showing footer nor any error vue.js file https://codeshare.io/YL7jXn
> 
> Can you help please @sohamsshah @iamrajiv

Basically, we need to create a footer component under `components` folder. Then in `LandingPage.vue` component, we need to add the component. It is at `FLINT-UI\flint.ui\src\views\Landing.vue`. Moreover, make sure to use `tailwindcss` classes ONLY for it.

**Comment by anjali1102** [comment]
> Then in `LandingPage.vue` component, we need to add the component. It is at `FLINT-UI\flint.ui\src\views\Landing.vue`. 









![moja-global-added-footer](https://user-images.githubusercontent.com/56559378/142870379-dd229eca-1b2d-4804-aeb4-de1a9e5c735e.PNG)

Done ✅

**Comment by anjali1102** [comment]
![moja-global](https://user-images.githubusercontent.com/56559378/142870621-4d09081f-a762-4104-90f5-02a76fdf9b72.PNG)
THen it started showing this, so i did **npm install --save mdbvue** after seeing error on web. but life is hard.
Landing.vue https://codeshare.io/YL7Nrn

**Comment by anjali1102** [comment]
@sohamsshah Please see once

**Comment by sohamsshah** [comment]
Hey @anjali1102 , as mentioned in the issue itself, we want to use *only* tailwindcss and slowly we want to completely migrate from *mdbvue* to ensure consistency with web design. So I would encourage you to use only tailwindcss classes (like how the Navbar and other sections of Landing Page are made) for creating Footer. (and remove extra dependency in case if added in package.json) Let me know if you need any assistance for solving this. Thanks

**Comment by padmajabhol** [comment]
Is someone working on this?

**Comment by chicken-biryani** [comment]
@padmajabhol nope. You can take it up.

**Comment by pragyamittal0** [comment]
Hi, I am Pragya, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by chicken-biryani** [comment]
Hey, @pragyamittal0 great work.

Although, A few pointers to keep in mind from here onwards:

- I guess @padmajabhol was already working on the issue. It's just open source etiquettes to ask- "Hey, can I work on this issue?" To the person who's been assigned the issue or to a maintainer.

- Always wait for a maintainer to reply before opening a PR because it may happen that there are some changes or some additional information that you may need for the PR.


I'll let @padmajabhol decide on what to do with the PR.


You should join our UI working group meeting today at 4pm.

Please join our slack and the #user-interface channel to recieve the link for the meeting.

https://t.co/tc684LtWj3

**Comment by padmajabhol** [comment]
Hey, I'm working on this, I had already proceeded with tailwind but I shall be redoing it with ant design with a little more time.
