### ISSUE TITLE
Feature Request: Integrate Hadolint for Docker linting

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/FLINT-UI#120]
### Is your feature request related to a problem? Please describe.

Hadolint is a tool for linting Dockerfiles. To know more about it, visit here: https://github.com/hadolint/hadolint

We would like to integrate Dockerfile linting as part of our CI pipeline to discover static issues and resolve them.

### Describe the solution you'd like.

Use the Hadolint action, referenced here: https://github.com/marketplace/actions/hadolint-action

Add it to [main.yml](https://github.com/moja-global/FLINT-UI/blob/master/.github/workflows/main.yml) and configure it to run with `flint.ui/Dockerfile`.

**Comment by asmijafar20** [comment]
I would like to work on this.

**Comment by HarshCasper** [comment]
Fixed in #122
