### ISSUE TITLE
Feature Request: Create core E2E for the FLINT-UI project

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/FLINT-UI#123]
### Is your feature request related to a problem? Please describe.

As of now, the project lacks any core E2E testing. We would need a consistent E2E testing strategy to test our features over CI before rolling it out in the production.

### Describe the solution you'd like.

We would like it to use [Cypress](https://cypress.io/). The contributor who is planning on doing it should plan the core features that need to be tested, identify the user story and integrate this with the CI.

### Additional context.

This issue can be kept open for contributors participating with Moja global on behalf of student-run open-source programs.

**Comment by sohamsshah** [comment]
Hey @HarshCasper , I would like to take this up. Can you please assign me?

**Comment by padmajabhol** [comment]
Can I work on this if this is still open?
