### ISSUE TITLE
DOCS: Document the process for deploying FLINT-UI on a free-tier EC2

### ISSUE THREAD

**Issue by vedant-kakde** [moja-global/FLINT-UI#125]
This process involves few basic steps:

- Writing scripts to setup necessary tooling on a fresh instance (Docker, Compose, Git and more)
- Setup FLINT-UI on the instance by following all the steps outlined on README
- Expose the running application publicly to run basic workloads
- Have a nice CI/CD setup to pull latest changes from GitHub, build the Docker container once again

**Comment by HarshCasper** [comment]
cc: @aornugent @iamrajiv

**Comment by aornugent** [comment]
Thanks @vedant-kakde. Please note that you also need to spin up an instance of [FLINTcloud](https://github.com/moja-global/flint.cloud/). We've had some trouble getting our client to communicate with remote instances (see: #118) so would love to know if you manage to resolve this issue by deploying both in the same cloud.

**Comment by HarshCasper** [comment]
Closing this issue because of no updates.
