### ISSUE TITLE
GCBM workflow and wireframe

### ISSUE THREAD

**Issue by chicken-biryani** [moja-global/FLINT-UI#128]
### **The core steps of the GCBM workflow**

This issue helps to keep everyone on the same page about what parts of the Flint UI-GCBM we are currently planning on improving/developing.

### Please note that:
1) FLINT-UI is a community-driven project and all contributions towards improving the FLINT-UI are welcome.
2) If you feel stuck, chat with us on Slack.
3) The document linked below is updated from time to time.

### 

#### Outside the UI
1. Define your local domain of interest (ie. where is the simulation taking place.)
2. Choose the model you want to run (i.e. which GCBM modules do you want to include)
3. Create the input files such as growth rates, disturbances etc.

#### Inside the UI
4. Configure the local domain
5. Configure the variables to accept your input files
6. Review the starting points for each pool
7. Set the spin up parameters for each pool
8. Optionally, review the advanced settings

#### Dispatched to FLINTcloud
9. Run the simulation

#### Outside the UI
10. Review the results

**We’re currently focusing on developing steps 4 to 8 in the UI.** **This [document](https://docs.google.com/document/d/1unpnMrhC3SgG6L60cDC8wsUWiIr4qfmeBeEsIe55sjQ/edit#heading=h.77ptruj3h9zb) further expands those steps.**
You can know about the rest of the steps in detail with the help of the documentation and videos focused on the GCBM.

### Wireframe

This is a very rough sketch of how this might work is presented at https://wireframe.cc/rLPTTX

**Comment by YashKandalkar** [comment]
Hey, @aornugent I had a few questions regarding the input files for the simulation.
1. Is Step 5 mentioned here the same as the Providers config in the [gcbm.js file](https://github.com/moja-global/FLINT-UI/blob/fa8a8779faaf6e86cf0ab9fb9273f0ff74a6993a/flint.ui/src/store/modules/gcbm.js#L237)? 
2. As you suggested, the preprocessing and template config generation can be done on the backend, then the only things that are supposed to be uploaded on the frontend are the GCBM input database and the layers files correct? 
3. Does the template config generation from a `.tiff` file require a lot of computation? I wanted to know if we can send the JSON config for all files in the response on the `/gcbm/upload` endpoint itself. 
    Or, if this task requires a lot of time, it can be done in the background and the result can be saved in different files by assigning each uploaded file a unique id. The frontend can show a button "Preview Config" below each uploaded file which will then send a new request to the backend for fetching the JSON config for that file. If the task is not complete yet, the server can send an error code, or send the JSON output otherwise. 
    After the frontend receives the JSON, it can be parsed and the user can edit the JSON config with a **user interface** (proper inputs can be created based on the value type of the JSON) or **directly inside JSON**.
    The interface will help the users who are not comfortable in editing the JSON values directly, while also letting the users edit the JSON values directly if they want. Both these tabs will be synchronised. What do you think?

**Comment by chicken-biryani** [comment]
@YashKandalkar the wireframe under this issue will be of huge help on what is to be worked on.

**Comment by chicken-biryani** [comment]
.
