### ISSUE TITLE
Numeric configuration values are not type-safe

### ISSUE THREAD

**Issue by aornugent** [moja-global/FLINT-UI#13]
@shubhamkarande13 discovered that JS is lazy and treats floats with no decimal place as integers (i.e. 0.0 = 0). The FLINT does not like this and, worse, uses a mixture of integers and floats in it's configuration.

Currently the solution is to wrap all floats with special characters (`$$`) but this is undocumented and might be difficult to manage as our application grows in complexity. Alternative solutions are welcomed.

**Comment by ErrolFernandes** [comment]
check whether this may work
https://mikemcl.github.io/decimal.js/
