### ISSUE TITLE
Feature Request: update the landing page of Flint UI according to the new design

### ISSUE THREAD

**Issue by YashKandalkar** [moja-global/FLINT-UI#155]
### Is your feature request related to a problem? Please describe.

The current landing page of Flint UI is not in accordance with the [new design](https://www.figma.com/proto/JXB1KKGWxD2dLR7dx2hqWS/Flint-UI?node-id=3%3A2&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=3%3A2).

There are some things that needs to be changed:
- The font currently being applied is Roboto but should me DM Sans.
- The landing banner is not of the correct height (has more padding than needed), 
- The landing text is not of the correct size
- The font color and line height in the 3 LandingPageCard components are not according to the new design.
- The Button component created in [this](https://github.com/moja-global/FLINT-UI/issues/111) PR can be used instead of the current "Explore" button (router link).

### Describe the solution you'd like.

Most of the issues require some style changes, and the Button component can be imported in [LandingPageCard.vue](https://github.com/moja-global/FLINT-UI/blob/master/flint.ui/src/components/Cards/LandingPageCard.vue) and used for redirecting to the appropriate link (with a new onClick method)

### Describe alternatives you've considered

-

### Additional context.

Current UI of landing page:
![image](https://user-images.githubusercontent.com/35102959/156052945-481e9a55-f571-417d-9fdc-353e17fbaf51.png)

UI after making changes:
![image](https://user-images.githubusercontent.com/35102959/156053094-85ece502-4c68-476e-b677-6b5232967249.png)

Similar changes can be made to the banner to match the new design.

**Comment by YashKandalkar** [comment]
@chicken-biryani can I work on this? Let me know if I missed anything or if any changes are required!

**Comment by chicken-biryani** [comment]
Hey @YashKandalkar looks great. Can you make sure they lead to the correct pages?

**Comment by YashKandalkar** [comment]
@chicken-biryani  Will do! Thanks!
