### ISSUE TITLE
Feature Request: Add the Button component in storybook.

### ISSUE THREAD

**Issue by YashKandalkar** [moja-global/FLINT-UI#156]
### Is your feature request related to a problem? Please describe.

Currently the Button visible in storybook is an example story added when first StoryBook.js was added to the repo (#32). This file can be replaced with the Button component that was created for the new design.

### Describe the solution you'd like.

We can replace `stories/Button.stories.js` with `stories/Button/Button.stories.js`, which is the button we will be using for the new design. 

### Describe alternatives you've considered

-

### Additional context.

There may be some changes required before the Button component is properly visible on storybook (run `yarn storybook` to check if the Button component is properly rendered with different props in storybook).

**Comment by SanjaySinghRajpoot** [comment]
May I work on this issue?

**Comment by SanjaySinghRajpoot** [comment]
I am a little confused on this issue. I compiled the code and the code was running in the storybook interface so is that is the place where I have to add the button OR do I have to create a new file for the button itself? Please let me know further instructions.

**Comment by tanay123456789** [comment]
As it has been 1 month since this issue was first opened and there is no progress so it is my humble request to maintainers to let me work on this issue.
