### ISSUE TITLE
Feature Request: Update DatepickerPoint.vue component based on the new design

### ISSUE THREAD

**Issue by YashKandalkar** [moja-global/FLINT-UI#160]
### Is your feature request related to a problem? Please describe.

The current DatepickerPoint.vue component (components/Datepicker/DatepickerPoint.vue) is not according to the new design.

### Describe the solution you'd like.

Change the UI of DatepickerPoint component to match the new design.

### Describe alternatives you've considered

-

### Additional context.

Current UI:
![image](https://user-images.githubusercontent.com/35102959/156228456-b2904fb9-fe07-4e79-9056-babc21edde61.png)

New UI from the design:
![image](https://user-images.githubusercontent.com/35102959/156228532-b081d038-693f-48e0-9d75-f148e67ae6b7.png)

Related discussion: https://github.com/moja-global/FLINT-UI/discussions/154

**Comment by ishitakeshawani** [comment]
I want to solve this issue. Can I?

**Comment by chicken-biryani** [comment]
Yes, @ishitakeshawani go ahead! :)

**Comment by Iheanacho-ai** [comment]
hey please is this issues still opened , if it is can i please work on it

**Comment by YashKandalkar** [comment]
Hey @Iheanacho-ai sorry, there was another issue made for making this component using ant design (https://github.com/moja-global/FLINT-UI/issues/177). 
@chicken-biryani can you close this one?
