### ISSUE TITLE
Feature Request: Update UI of `/flint/configurations/rothc` according to the new design

### ISSUE THREAD

**Issue by YashKandalkar** [moja-global/FLINT-UI#162]
### Is your feature request related to a problem? Please describe.

Current UI is not according to the new design.

### Describe the solution you'd like.

TODO:
- Add Navbar (components/Navbars/LandingPageNavbar.vue)
- Remove gradient
- Fix margins, padding
- Typography (color, size, etc.)
- Remove Stepper component (not in the new design)

### Describe alternatives you've considered

-

### Additional context.

Note: Keep the configuration components as it is, the RothCTemplate component can be covered in another issue.

Related discussion: https://github.com/moja-global/FLINT-UI/discussions/154

**Comment by SanjaySinghRajpoot** [comment]
May I work on this issue?

**Comment by chicken-biryani** [comment]
Yes, @SanjaySinghRajpoot!

But do complete the issues you take up!
