### ISSUE TITLE
Feature Request: Move configurations/rothc/* views to components/Configurations/RothC/ and update UI

### ISSUE THREAD

**Issue by YashKandalkar** [moja-global/FLINT-UI#163]
### Is your feature request related to a problem? Please describe.

Currently, configurations/rothc/* are in views/ directory. But in the new design, all of these configurations are on the same page.

### Describe the solution you'd like.

TODO:
- Move files from views/configurations/rothc/* to components/Configurations/RothC/
- Update the UI of the configuration components to match the new design (You can directly edit the views/configurations/rothc/* files before moving them to components/ to see your UI changes on the appropriate paths. Copy the updated files into the components/ folder).

### Additional context.

Related discussion: #154

**Comment by YashKandalkar** [comment]
Once a PR for this is merged we can work on creating smaller components out of the inputs/textareas in these config files since a lot of the code is repeated for different configurations.

**Comment by aliya-rahmani** [comment]
@YashKandalkar Can I work on this issue?

**Comment by chicken-biryani** [comment]
@aliya-rahmani yes! Go ahead!

**Comment by YashKandalkar** [comment]
Hey @aliya-rahmani as discussed on Slack (https://github.com/moja-global/FLINT-UI/discussions/154) we are creating smaller components using ant-design, so we first need to make smaller components which RothC components uses. We will be creating issues for these components you can take one to work upon if you want:)
 You can also stay active in the #user-interface channel of slack for getting updates!
