### ISSUE TITLE
Feature Request: Create Slider component in Ant Design 

### ISSUE THREAD

**Issue by SanjaySinghRajpoot** [moja-global/FLINT-UI#175]
### Is your feature request related to a problem? Please describe.

Create a new Slider component using Ant Design. Kindly make the required changes. 

### Describe the solution you'd like.

This component will only change the colour of rail and the dot to the colours from the new design (in the diagram above) and directly render ant-design-vue (antdv)’s Slider component. 

Props:
All props of antdv’s Slider component
dotColor prop - for changing handle (dot) color
trackColor prop - for changing track color
railColor prop - for changing rail color

### Additional context.
![Screenshot from 2022-03-11 11-22-03](https://user-images.githubusercontent.com/67458417/157810493-7234ffcf-b5e9-4036-a7e9-f11678f64760.png)

This is how the slider component should look like.

**Comment by arpita221b** [comment]
Hey!! 
I would like to work on this issue can you please assign this to me?

**Comment by chicken-biryani** [comment]
Yes, @arpita221b please go ahead!

**Comment by chicken-biryani** [comment]
Hey, @arpita221b if you would have started solving the issue you may have realised that we already have the component.

I am sorry for the confusion. I'll have to close this issue.

**Comment by arpita221b** [comment]
No problem!!
