### ISSUE TITLE
Feature Request: Create DatePickerPoint Component in Ant Design 

### ISSUE THREAD

**Issue by SanjaySinghRajpoot** [moja-global/FLINT-UI#177]
### Is your feature request related to a problem? Please describe.

Create a DatePickerPoint component using ant-design-vue's DatePicker component based on the new design. Make all the required so that the new component look as close to the design described below. 

link - https://www.antdv.com/components/date-picker/

### Describe the solution you'd like.

Making a new DatePickerPoint component using Ant Design. There are plenty of examples on the Ant Design website that can be used as the reference for this component. 

### Additional context.

![Screenshot from 2022-03-11 11-30-45](https://user-images.githubusercontent.com/67458417/157811332-98e83c7d-ab68-4fad-b862-ef6f2071f6dd.png)

**Comment by padmajabhol** [comment]
I'd like to work on this.

**Comment by chicken-biryani** [comment]
@padmajabhol is it okay if we keep this one for the new contributors?

**Comment by padmajabhol** [comment]
Sure! I just saw the good first issue now 😅

**Comment by arnab15** [comment]
@chicken-biryani i would like to work on this issue please assign it to me.

**Comment by chicken-biryani** [comment]
@arnab15 do wait till the Date picker issue is merged.

**Comment by arnab15** [comment]
Does this issue have any peer dependency on the Date picker? @HarshCasper @chicken-biryani

**Comment by chicken-biryani** [comment]
@arnab15 we want #174 to get comoleted before we move on to this one.

**Comment by YashKandalkar** [comment]
Hey @arnab15 ! Hope you're doing well!
Since https://github.com/moja-global/FLINT-UI/issues/174 was merged recently, you can use that Datepicker in this DatePickerPoint component. Let us know if you need any help!

**Comment by arnab15** [comment]
@chicken-biryani @HarshCasper @YashKandalkar if possible please assign this issue to any other contributors as I'll not be able to complete it.

**Comment by chicken-biryani** [comment]
Hi, @arnab15 sure.

Can you please just put it over slack, #user-interface channel so that people know that they can take it up?
Thanks!

**Comment by joharikushagra** [comment]
@chicken-biryani may I take this issue?

**Comment by chicken-biryani** [comment]
@joharikushagra yess!

**Comment by joharikushagra** [comment]
@chicken-biryani I tried setting up project as mentioned in installation guide, but unable to docker-compose the image as I'm low on disk storage. Is there any other alternative?

**Comment by chicken-biryani** [comment]
Hi, @joharikushagra maybe getting rid of programs you don't currently need?

**Comment by YashKandalkar** [comment]
@joharikushagra if you just want to work of flint.ui you can just clone this repo, cd into flint.ui and run `yarn` then `yarn serve` to start the vue app. 
Since this is just a UI issue only starting flint.ui vue app will work.
