### ISSUE TITLE
Feature Request: Create a new Table using Ant Design 

### ISSUE THREAD

**Issue by SanjaySinghRajpoot** [moja-global/FLINT-UI#178]
### Is your feature request related to a problem? Please describe.

The table component on the FLINT-UI website is outdated. It needs to be updated as per Ant Design Layout. 

### Describe alternatives you've considered

We need a new table component to show all the data from the simulation. For this, we will use Ant Design Table Component. The Color and the text of the table component can be modified as per our needs. 

### Additional context.

![Screenshot from 2022-03-11 11-33-42](https://user-images.githubusercontent.com/67458417/157811630-575b74a4-0837-45c9-ac03-e1170101e239.png)

**Comment by SanjaySinghRajpoot** [comment]
I would like to work on this issue. 

Thank You

**Comment by sayan011** [comment]
Hey @SanjaySinghRajpoot  ,can I work on this issue?

**Comment by chicken-biryani** [comment]
@sayan011 yes. Go ahead!
Please keep us updated about your progress.

**Comment by chicken-biryani** [comment]
Hi @sayan011 how are you prgressing? If you're facing any trouble do let me know.

**Comment by sayan011** [comment]
I'm not too familiar with Vue.. I'm learning it on the fly, that's why it's taking some time.. But I think I can finish it by Wednesday.....will definitely let you know if I face any trouble...sorry for the delay.

**Comment by aniketh-varma** [comment]
Hi, I would like to work on this issue. I am a part of OpenForce 2022 and would be needing some documentation or help to get started with the issue.

**Comment by chicken-biryani** [comment]
Hi, @aniketh-varma we are there to help you out. How comfortable with Vue?

**Comment by chicken-biryani** [comment]
@aniketh-varma I believe developing this component can be a little tough but can be a good learning process.

@SanjaySinghRajpoot and @YashKandalkar would you be okay with guiding him over slack?

**Comment by chicken-biryani** [comment]
@aniketh-varma have you joined our slack? If not please join it.

And send a message to me over there.

**Comment by ritikalohia** [comment]
Is this issue opened? is it Assigned to someone,? if not. can you please assign me this task? @chicken-biryani

**Comment by chicken-biryani** [comment]
Hi, @ritikalohia it is open. You can work on it.

Do reach out to us on Slack if required.

**Comment by padmajabhol** [comment]
Any updates on this @ritikalohia ? Please reach out to us if you need help.

**Comment by ritikalohia** [comment]
yeah, i really need help at this time. I am familiar with vue.js but dont know how to handle antdesign with  vue.

**Comment by padmajabhol** [comment]
@ritikalohia , please ping me on slack.

**Comment by YashKandalkar** [comment]
@chicken-biryani Table components are added in #271 & #276, this can be closed
