### ISSUE TITLE
Feature Request: Fix padding and Positon of Text on `Rothc` page 

### ISSUE THREAD

**Issue by SanjaySinghRajpoot** [moja-global/FLINT-UI#182]
### Is your feature request related to a problem? Please describe.

`Rothc` page has a few differences when we compare it with the Figma Design.

### Describe the solution you'd like.

Fix the padding, margin and font design to match the Figma design template. Make all the required changes so that the`rothc` page resembles the design template. 

### Additional context.

Expected Design: 
![Screenshot from 2022-03-16 12-03-07](https://user-images.githubusercontent.com/67458417/158530605-c0bbe8db-db56-4b23-9be8-69c60393b687.png)

**Comment by SanjaySinghRajpoot** [comment]
Only for beginners. !!

**Comment by Palaksharma23** [comment]
@chicken-biryani maam i would love to work on this issue, can I take this up :)

**Comment by chicken-biryani** [comment]
@Palaksharma23 yes.

Do keep us updated if you get stuck, okay?

**Comment by Palaksharma23** [comment]
@chicken-biryani sure maam
