### ISSUE TITLE
Feature Request: Create a new Accordion Component Using Ant Design

### ISSUE THREAD

**Issue by SanjaySinghRajpoot** [moja-global/FLINT-UI#183]
### Is your feature request related to a problem? Please describe.

The current website has the Card component which needs to be changed with the Accordion component from the Ant Design. It has to be updated as per the new design. Drop down should work as expected along with the required fields. Dropdown

### Describe the solution you'd like.

Making a new Accordion component using Ant Design. Implementing it in the Vue.js file. 
Collapse - A content area that can be collapsed and expanded.
- Props for the heading Text
- Props for the Dropdown Text
- Props for Column Data 

Link - https://ant.design/components/collapse/

### Additional context.

Expected: 
![Screenshot from 2022-03-16 12-06-07](https://user-images.githubusercontent.com/67458417/158531300-f8886fa5-c87c-46a9-9063-800f8d2e4a3d.png)

**Comment by arpita221b** [comment]
Hey!!
I would like to work on this issue!!

**Comment by chicken-biryani** [comment]
Hi @arpita221b yes. You can work on it.

(Hopefully nothing goes wrong this time! 😅😂)

**Comment by arpita221b** [comment]
Let's see 😂😂

**Comment by Janvi-Thakkar** [comment]
@arpita221b Please let me know if I could help you, I would love to do so!

**Comment by sohamsshah** [comment]
Hi @arpita221b , are you working on this? In case if you are occupied and do not have enough bandwidth, it's fine, you can take up other issues later. We can unblock this issue to make room for other contributors to be assigned.

**Comment by chicken-biryani** [comment]
Hi @sohamsshah @arpita221b had updated me over slack yesterday.

Since colleges have started offline for her she'll be taking care of the issue by coming Sunday.

I think we can wait till then.

**Comment by sohamsshah** [comment]
Makes sense @chicken-biryani , no problem!

**Comment by chicken-biryani** [comment]
Hi @arpita221b are you facing any difficulties?

**Comment by chicken-biryani** [comment]
@arpita221b would you be okay with someone else working on this issue?

**Comment by anamika-yadav99** [comment]
Hi @chicken-biryani. I'm an outreachy applicant. I have finished the recommended task. I see all the issues have been assigned. Since there is no response from @arpita221b . Can I take up this one?

**Comment by arpita221b** [comment]
@chicken-biryani Hey Shloka I am so sorry I wasn't active for so many days.
I texted you on slack that you can assign this issue to someone else, because I had to do some other work. Sorry :'(

**Comment by YashKandalkar** [comment]
I'd like to work on this!
