### ISSUE TITLE
Bug: Logo is not clickable

### ISSUE THREAD

**Issue by Janvi-Thakkar** [moja-global/FLINT-UI#188]
### Describe the bug.

For better UX, it is common practice that by clicking on the logo of the header section, the user should be redirected to the landing page of the website. This would help users to navigate easily.

### Describe the steps to reproduce the behavior.

1) Open the Flint-UI website
2) Click on the logo of the header section.

### Expected behavior.

By clicking on the logo user should be redirected to home page/ landing page of the website.

### Operating Environment

Windows 10 - Chrome browser

**Comment by Janvi-Thakkar** [comment]
I would like to work on this.

**Comment by chicken-biryani** [comment]
Hi, @Janvi-Thakkar that's a really good start.

@SanjaySinghRajpoot and @YashKandalkar would you like to guide @Janvi-Thakkar on how to accomplish the above in a way we require.

Thanks!

**Comment by Janvi-Thakkar** [comment]
> Hi, @Janvi-Thakkar that's a really good start.
> 
> @SanjaySinghRajpoot and @YashKandalkar would you like to guide @Janvi-Thakkar on how to accomplish the above in a way we require.
> 
> Thanks!

@chicken-biryani Thank You! Is there any specific expectation to accomplish it?

**Comment by YashKandalkar** [comment]
@Janvi-Thakkar Not really, just wrapping the logo's img in an anchor tag should work! 
Let us know if you need any help. 
Thanks for creating the issue!

**Comment by Janvi-Thakkar** [comment]
> @Janvi-Thakkar Not really, just wrapping the logo's img in an anchor tag should work! Let us know if you need any help. Thanks for creating the issue!

@YashKandalkar Okay, I will send the PR soon and let you know if I need help in between.
