### ISSUE TITLE
Feature Request: Updating Footer Component 

### ISSUE THREAD

**Issue by SanjaySinghRajpoot** [moja-global/FLINT-UI#190]
### Is your feature request related to a problem? Please describe.

The current `footer` component looks outdated with respect to the community website's footer.  The bg-color does not match the theme of the website. Few links are also missing on this Footer component. 

### Describe the solution you'd like.

Update the footer component so it looks similar to the Community website's footer. This will make the site more uniform with respect to other web pages. Adding new links and text properties. 

### Additional context.

Expected:
![Screenshot from 2022-03-19 18-53-46](https://user-images.githubusercontent.com/67458417/159123122-a39cb9be-9015-4416-a76e-96785d1684a6.png)

**Comment by SanjaySinghRajpoot** [comment]
I would like to work in this issue

**Comment by manekasingh05** [comment]
I would like to work on this issue under Codeflow codeforce 2022

**Comment by chicken-biryani** [comment]
Hia, @manekasingh05 this is already been worked on.

What you can do is take inspiration from Janvi who created issue #188

She has set up the project and looking for small details that are missing. Maybe you could do something similar.
