### ISSUE TITLE
Bug: different pages have different padding for header.

### ISSUE THREAD

**Issue by Janvi-Thakkar** [moja-global/FLINT-UI#191]
### Describe the bug.

The padding of division around the header is different for different pages, which makes the UI inconsistent.

### Describe the steps to reproduce the behavior.

1. Open Flint.UI home page
2. Notice the header.
3. Go to Point /RothC / GCBM page.
4. Notice the header's start and endpoints.

### Expected behavior.

The header should be consistent across the pages.

### Screenshots.

![image](https://user-images.githubusercontent.com/55620053/159133252-503c3b0c-8d69-47d8-84c2-a9abfa2b0971.png)

![image](https://user-images.githubusercontent.com/55620053/159133071-4c861af0-1ef7-4259-8fcb-9e3d51a8a175.png)

### Operating Environment

Windows 10 - Chrome browser

**Comment by Janvi-Thakkar** [comment]
@chicken-biryani I would like to work on this. Can you please assign this to me?

**Comment by chicken-biryani** [comment]
Good catch @Janvi-Thakkar. Please go ahead and work on it.
