### ISSUE TITLE
Bug: Elements of RothC page are not aligned

### ISSUE THREAD

**Issue by Janvi-Thakkar** [moja-global/FLINT-UI#193]
### Describe the bug.

Elements alignment enhances visibility and usability. So it is necessary to provide proper alignment.

### Describe the steps to reproduce the behavior.

1. Go to home page of FLINT.UI
2. Click on explore button for RothC section.
3. Check the visual alignment of the page.

### Expected behavior.

Elements on the page should be aligned.

### Screenshots.

![image](https://user-images.githubusercontent.com/55620053/159139146-2e781e16-1cc3-4242-b66a-1a88d1de90fe.png)

### Operating Environment

Windows 10 - Chrome browser

**Comment by SanjaySinghRajpoot** [comment]
This issue is already fixed in #182. Have a look and take the Pull from master branch.
