### ISSUE TITLE
Documentation: Add code of conduct.

### ISSUE THREAD

**Issue by chicken-biryani** [moja-global/FLINT-UI#195]
We don't have the code of conduct in FLINT-UI.

Please take help of the link below.
https://github.com/moja-global/About_moja_global/blob/master/CODE_OF_CONDUCT.md

**Comment by aornugent** [comment]
Hey @chicken-biryani - the moja global Code of Conduct applies to all of our projects, so we don't need to write a new one. 

Maybe just a link is needed? Also found at: 
* https://community.moja.global/community/code-of-conduct
* https://docs.moja.global/en/latest/contributing/coc.html

**Comment by aornugent** [comment]
But! I noticed the email address in the Enforcement section is wrong. We need to change guy@moja.global -> mentorship@moja.global across all three versions.

**Comment by chicken-biryani** [comment]
@aornugent yes the link provided just requires the person to copy and paste from the code of conduct given at 'About moja global' into a markdown file named 'Code of Conduct' and not write up a new one.

**Although**, just linking the 'code of conduct' document in a markdown does seem like a better idea because if it wouldn't have to be updated at multiple places.

Correct?

**Comment by aniketh-varma** [comment]
Hi @chicken-biryani, I would like to take up this issue. Also, it would be helpful if you can please clarify if a new Code of Conduct has to be added or simply a link to the Code of Conduct would be fine. Thanks.

**Comment by chicken-biryani** [comment]
Hey, @aniketh-varma thank you for taking it up.

To clarify:

- Create a md file named 'CODE_OF_CONDUT'
- Add a sentence something along the lines 'All members are asked to follow the code of conduct'.
- Link the code of conduct document.

Take help of this PR - https://github.com/jupyter-naas/naas/pull/298 

(Be careful of the wordings.)

**Comment by Iheanacho-ai** [comment]
hey is this issue currently worked on, can i work on this ?
