### ISSUE TITLE
Bug: Remove unnecessary `MainNavbar.vue` and `Footer.vue` files from the codebase

### ISSUE THREAD

**Issue by sohamsshah** [moja-global/FLINT-UI#197]
### Describe the bug.

Currently, our codebase doesn't use `Navbars/MainNavbar.vue` and `Alert/Footer.vue` component and also it is implemented in tailwindcss. So, it is a good idea to remove it from the project.

### Operating Environment

N/A

### Additional Information

The file is present as `FLINT-UI\flint.ui\src\components\Navbars\MainNavbar.vue` and `FLINT-UI\flint.ui\src\components\Alert\Footer.vue`. Before removing make sure this change doesn't break the build or dev of the project.

**Comment by InfiniteVerma** [comment]
I'd like to work on this.

**Comment by sohamsshah** [comment]
Sure @InfiniteVerma , please go ahead! Let me know if you need any help

**Comment by InfiniteVerma** [comment]
To test the changes, is running the Vue app enough?

**Comment by sohamsshah** [comment]
> To test the changes, is doing the E2E testing enough?

Yes E2E should be done. Though, currently not all pages are covered by E2E, you can run `yarn dev` and if nothing breaks then it is good to go.
