### ISSUE TITLE
Bug:  Change colour theme of GCBM step 2 and step 3 as per new UI

### ISSUE THREAD

**Issue by Janvi-Thakkar** [moja-global/FLINT-UI#198]
### Describe the bug.

Color theme for GCBM step 2 and step 3 is not same as other pages of FLINT.UI

### Describe the steps to reproduce the behavior.

1. Go to the landing page of FLINT.UI
2. Click of Explore button for GCBM
3. Go to Upload dataset step
4. See the difference
5. Check the behavior for Run | Check status | Download step as well 

### Expected behavior.

UI color theme should be consistent across every page of the app. Please check the screenshots attached below to get idea about the expected colors. Please try to change the colors of GCBM steps 2 and 3 as per the GCBM step1.

### Screenshots.

Current colors 

GCBM step 2 
![image](https://user-images.githubusercontent.com/55620053/159333094-5f00c76a-5ce1-48b6-8b53-fdc52ab695fe.png)

GCBM step 3
![image](https://user-images.githubusercontent.com/55620053/159333209-dce65318-07e8-4719-933d-6e373c5bef2f.png)

Expected colors (GCBM step 1)
![image](https://user-images.githubusercontent.com/55620053/159347024-4485cfbe-76c5-4c7b-8611-a663e0a6a3d5.png)

### Operating Environment

Windows 10 - Chrome browser

### Additional Information

This behavior can be checked by going to http://localhost:8000/gcbm/run and http://localhost:8000/gcbm/upload as well while working in the local environment.

**Comment by chicken-biryani** [comment]
Hi, @Janvi-Thakkar it isn't indicated anywhere what the 'new color theme' is like.

For someone who is new may feel a little lost. Could you add a link to how the new color theme should be? Also are you familiar with Figma? Maybe designing and indicating how the first page should be may be a good move?

If you aren't familiar with Figma you and @shriya can team up. And work on a design for the first page... (Starting with the color theme.)

It may be a good exercise for both of you.

**Comment by Janvi-Thakkar** [comment]
@chicken-biryani Yes, I should add what the new color theme is. Actually, I have mentioned that the colors on those pages differ from other pages of the FLINT.UI, even the 1st step of GCBM is having normal colors. 

But you are right that beginners would not be aware of how they should change the colors. I am knowing the Figma. I have worked a little with it. But if I can provide screenshots of other pages, then the color difference would be clearly visible. 

Should I provide Figma Design in that case?

**Comment by chicken-biryani** [comment]
@Janvi-ThakkarYou're correct! What we could do is--

Add a screenshot of what the color should look like. In that case, we won't require a Figma design. And a new person can work on this issue.

Good thinking!

**Comment by Janvi-Thakkar** [comment]
@chicken-biryani I will add the screenshot of 2-3 pages to let them know the expected colors. 

I can surely design the component if we want to revamp the UI but I should create another issue for that!

**Comment by chicken-biryani** [comment]
@Janvi-Thakkar yes. That will take some time and also some brainstorming.

But is worth it!

**Comment by chicken-biryani** [comment]
@Palaksharma23 would you like to try out this issue?

**Comment by Janvi-Thakkar** [comment]
@Palaksharma23 please let me know if you are facing any hurdles. I would be happy to help you!

**Comment by Palaksharma23** [comment]
sure @Janvi-Thakkar :)
