### ISSUE TITLE
Refactor: `Footer.vue` component has inline styling

### ISSUE THREAD

**Issue by sohamsshah** [moja-global/FLINT-UI#200]
### Is your feature request related to a problem? Please describe.

This Refactor (feature) request aims to fix the inline styling done via `style` html tags in the project. It is not a good practice to have inline css styling and thus a quick refactor to add corresponding css classes to the footer component would work.

### Describe the solution you'd like.

Add css styles in the `<style scoped>` tag of the component. Refer other components' implementation for the Footer.vue component.

The component is present at: `FLINT-UI\flint.ui\src\components\Footer\Footer.vue`

Also, the default export name is `LandingPageNavbar` instead of `Footer` component. This can also be refactored.

**Comment by Janvi-Thakkar** [comment]
@sohamsshah I would like to work on it. Can you please assign this to me?

**Comment by sohamsshah** [comment]
Sure @Janvi-Thakkar , please go ahead!
