### ISSUE TITLE
Feature Request: Redirect user to email when clicks on info@moja.global in footer

### ISSUE THREAD

**Issue by Janvi-Thakkar** [moja-global/FLINT-UI#204]
### Is your feature request related to a problem? Please describe.

We can provide a link to the mail id so it would be easier for users to contact the organization.

### Describe the solution you'd like.

Provide email link on the mail id in the footer.

**Comment by InfiniteVerma** [comment]
I'd like to work on this.

**Comment by chicken-biryani** [comment]
Go ahead! @InfiniteVerma

**Comment by Janvi-Thakkar** [comment]
@InfiniteVerma please let me know if you need any help!

**Comment by InfiniteVerma** [comment]
Hey @Janvi-Thakkar, thanks! I found the files to change. Will update you if I need help.

**Comment by chicken-biryani** [comment]
Hi @InfiniteVerma any updates?

**Comment by Iheanacho-ai** [comment]
hey please if this is free to work on can i work on this !

**Comment by chicken-biryani** [comment]
Hey @Iheanacho-ai it's already been worked upon. It's under review at the moment. Feel free to take up another.

**Comment by Timonwa** [comment]
Hi @chicken-biryani I fixed this when I worked on #278

**Comment by chicken-biryani** [comment]
Awesome. So we can close it.
