### ISSUE TITLE
Bug: Simulation length should be dynamic based on start and end date

### ISSUE THREAD

**Issue by Janvi-Thakkar** [moja-global/FLINT-UI#207]
### Describe the bug.

In Point and RothC pages, the simulation length is not changing dynamically. The static value 4.92 is used for simulation length.

### Describe the steps to reproduce the behavior.

1) Go to the landing page on FLINT-UI
2) Explore RothC or Point section
3) Check the behavior by changing the start and end dates

### Expected behavior.

Simulation Length should be calculated based on start and end dates.

### Screenshots.

![image](https://user-images.githubusercontent.com/55620053/160193162-a28ab676-39b6-455f-81b7-e3dd9e44a2e1.png)
![image](https://user-images.githubusercontent.com/55620053/160193926-5408b0aa-151d-4de8-8639-f2fca3cc38a2.png)

### Operating Environment

Windows 10 - Chrome browser

### Additional Information

My suggestion would be to use the moment.js library.

**Comment by soumyag123** [comment]
Hii @chicken-biryani can you please assign me this issue?

**Comment by chicken-biryani** [comment]
Hi, @soumyag123 yes. Go ahead!

**Comment by chicken-biryani** [comment]
@soumyag123 any updates?

**Comment by anamika-yadav99** [comment]
Hi @chicken-biryani. I'm an outreachy applicant. I have finished the recommended task. I see all the issues have been assigned but very few any updates even after 5 days. Can I take up any of the issue and create a PR or should I wait for new issue?

**Comment by chicken-biryani** [comment]
Hi @anamika-yadav99

Ideally, you should ask the person who has been assigned the issue first. If they don't reply within 2-3 days... Take up the issue.


Also, I believe moja global - outreachy is currently focusing somewhere else at the moment. Have you joined our slack and seen the Outreachy channel?

**Comment by anamika-yadav99** [comment]
@chicken-biryani sorry I deleted the comment as I felt it would not be good to take up the issue assigned to someone else.
 Yes, I have joined the slack channel and finished the task already. I was looking forward to contributing to the existing projects.There is no specific repo mentioned to work on for outreachy applicants because it's a pilot project. Can you guide me with the next step for outreachy?

**Comment by chicken-biryani** [comment]
Hi, @anamika-yadav99 it's okay to be unsure. But try not to delete comments.


Yes, I can try to guide you or help you out over the slack #outreachy channel.

**Comment by anamika-yadav99** [comment]
Thanks @chicken-biryani I have posted my question in the outreachy channel.

**Comment by Janvi-Thakkar** [comment]
Hello @soumyag123, Do you need any help?

**Comment by Janvi-Thakkar** [comment]
@chicken-biryani as the issue is idle for a long time, may I take this up? @soumyag123 are you with it?

**Comment by chicken-biryani** [comment]
@Janvi-Thakkar Yea go ahead!

**Comment by Janvi-Thakkar** [comment]
@chicken-biryani Thank You!
