### ISSUE TITLE
Bug: Changing the start date is causing automatic change in end date and vice versa in RothC

### ISSUE THREAD

**Issue by Janvi-Thakkar** [moja-global/FLINT-UI#208]
### Describe the bug.

Date picker's value for end date is getting changed by changing the start date as well and vice versa.

### Describe the steps to reproduce the behavior.

1) Go to the landing page on FLINT-UI
2) Explore RothC section
3) Check the behavior by changing the start and end dates

### Expected behavior.

Both dates should be changeable individually

### Screenshots.

![image](https://user-images.githubusercontent.com/55620053/160194177-8e957622-6eef-4812-a4e0-1b6a52040c90.png)
![image](https://user-images.githubusercontent.com/55620053/160194221-d2be6694-705e-4d76-a5f9-bbbd75b04e18.png)

### Operating Environment

Windows 10 - Chrome browser

**Comment by Janvi-Thakkar** [comment]
@sohamsshah @chicken-biryani can I work on this?

**Comment by chicken-biryani** [comment]
@Janvi-Thakkar yes please!
