### ISSUE TITLE
Bug: unnecessary margin right on DatepickerRothC's inputs

### ISSUE THREAD

**Issue by YashKandalkar** [moja-global/FLINT-UI#210]
### Describe the bug.

There is a `margin-right: 8em;` in DatepickerRothC's styles, which causes the configurations page to overflow.

### Expected behavior.

Remove `margin-right: 8em;` from `.datepicker-input` class in DatepickerRothC.vue. 
Also add `scoped` to the styles of DatepickerRothC component since this class was affecting date pickers in DatepickerPoint as well.

### Screenshots.

![datepicker-margin-bug](https://user-images.githubusercontent.com/35102959/160247377-f864b4a8-45a4-4cee-96c6-4d22fc78df60.png)

(Notice the bottom scrollbar)

### Operating Environment

Ubuntu 20.04

**Comment by Akshit42-hue** [comment]
Can I work on this issue @chicken-biryani @YashKandalkar

**Comment by chicken-biryani** [comment]
@Akshit42-hue yes please!
