### ISSUE TITLE
Footer year

### ISSUE THREAD

**Issue by Akshit42-hue** [moja-global/FLINT-UI#218]
### Describe the bug.

The current year setting at the footer is not dynamic I guess and that is why it is showing as 2021.
![Screenshot from 2022-03-30 15-45-48](https://user-images.githubusercontent.com/59443454/160810807-1d0e6555-e0e3-42e0-9654-c8bc73db51cc.png)

### Expected behavior.

The Year should change dynamically every year without the need to change it each year.

### Operating Environment

Linux

**Comment by Akshit42-hue** [comment]
Hey @chicken-biryani, Can I work on this issue ?

**Comment by chicken-biryani** [comment]
I am not sure.

@HarshCasper is that so?

**Comment by HarshCasper** [comment]
> I am not sure.
> 
> @HarshCasper is that so?

Definitely. Thanks for the catch @Akshit42-hue 👏

**Comment by chicken-biryani** [comment]
Hi @Akshit42-hue any updates?

**Comment by Akshit42-hue** [comment]
Hey @chicken-biryani , will raise a PR in this week

**Comment by Iheanacho-ai** [comment]
If you need any help @Akshit42-hue id be happy to help !

**Comment by Akshit42-hue** [comment]
Sure @Iheanacho-ai will discuss in slack

**Comment by Akshit42-hue** [comment]
Hey @chicken-biryani can you please give some hints on which file I want to change, I can't able to replicate the issue

**Comment by padmajabhol** [comment]
@Akshit42-hue You basically have to change [this](https://github.com/moja-global/FLINT-UI/blob/64f79d6c176788b98c19ac6facadb5b4fcbf1aa5/flint.ui/src/components/Footer/Footer.vue#L80)

**Comment by Akshit42-hue** [comment]
hey @padmajabhol thanks for joining the conversation
you are talking about flint-ui website 
![Screenshot from 2022-04-08 18-31-17](https://user-images.githubusercontent.com/59443454/162440925-15cca404-8173-4d7c-9dac-f8ea9f122dfb.png)
I am talking about moja global website
![Screenshot from 2022-04-08 18-32-40](https://user-images.githubusercontent.com/59443454/162441081-3d303c7e-e645-4787-9dfa-1d52bda3d048.png)

**Comment by chicken-biryani** [comment]
Hi @Akshit42-hue we don't make changes in the official moja global site.

Please try to keep changes to the Flint UI and community website.
