### ISSUE TITLE
Bug: Alignment of text and Dates is not proper for `RothC` page

### ISSUE THREAD

**Issue by SanjaySinghRajpoot** [moja-global/FLINT-UI#226]
### Describe the bug.

- Text Alignment is not proper. 

### Expected behavior.

Text Alignment should be proper

### Screenshots.
![Screenshot from 2022-04-09 15-44-09](https://user-images.githubusercontent.com/67458417/162567701-f32d043e-66e1-464c-9065-c12965d07674.png)

### Operating Environment

Ubuntu 20.04

**Comment by Janvi-Thakkar** [comment]
@SanjaySinghRajpoot @HarshCasper As it's not assigned yet to anyone, may I work on this if it's not limited to SheCodesAfrica?

**Comment by HarshCasper** [comment]
> @SanjaySinghRajpoot @HarshCasper As it's not assigned yet to anyone, may I work on this if it's not limited to SheCodesAfrica?

Its limited to SheCodesAfrica as of now.

**Comment by Janvi-Thakkar** [comment]
@HarshCasper, Okay.

**Comment by Timonwa** [comment]
Hi @HarshCasper can I take up this issue? I'm from SheCodeAfrica.
