### ISSUE TITLE
Feature Request: Add Environment Variables to the `FLINT-UI` project 

### ISSUE THREAD

**Issue by SanjaySinghRajpoot** [moja-global/FLINT-UI#227]
### Is your feature request related to a problem? Please describe.

All the URL needs to be updated with the new `dotenv.config();` variable. Currently, all these URL points to a localhost address which are not dynamic in nature. 

### Describe the solution you'd like.

- Update the URLs
- Replace static URL with dynamic URLs
- Add new `.env` file
- Install required dependencies. 

### Additional context.

![Screenshot from 2022-04-09 16-32-53](https://user-images.githubusercontent.com/67458417/162569445-28a9690d-1e40-4f3f-802c-e03186c466b2.png)

**Comment by jiisa-k** [comment]
Hello,
I'd like to work on this issue. Can it be assigned to me?
