### ISSUE TITLE
Bug: Extra width of configuration cards of RothC are causing appearance of horizontal scrollbar

### ISSUE THREAD

**Issue by Janvi-Thakkar** [moja-global/FLINT-UI#237]
### Describe the bug.

The outer division of configuration cards on RothC page is having 100% width, extra padding, and margin as well, which is causing the appearance of a horizontal scrollbar.

### Describe the steps to reproduce the behavior.

1) Open the Flint-UI homepage.
2) Explore the RothC page.
3) See the scrollbar with extra white space on scrolling.

### Expected behavior.

There should not be a horizontal scrollbar for the extra white space.

### Screenshots.

![image](https://user-images.githubusercontent.com/55620053/163648614-0900fcdd-d6df-4508-8119-4798b2fb74a8.png)
![image](https://user-images.githubusercontent.com/55620053/163648644-63dffc4f-f71b-4022-9fe3-2d9cedf91164.png)

### Operating Environment

Windows 10 - Chrome browser

**Comment by tewarig** [comment]
i think this might be happening because some element is overflowing on the y-axis... we can avoid such issues by using overflow-y: hidden  please assign this to me would love to fix this

**Comment by Janvi-Thakkar** [comment]
> i think this might be happening because some element is overflowing on the y-axis... we can avoid such issues by using overflow-y: hidden please assign this to me would love to fix this

Hello @tewarig, maybe you misunderstood. It's overflowing on the x-axis. Overflow of the y-axis can not affect horizontal content. So, overflow-y: hidden will not work in this case.

**Comment by tewarig** [comment]
yes i mean x axis only ... should have attended all maths classes... can i work on this ?

**Comment by Janvi-Thakkar** [comment]
It happens! Overflow-x:hidden would just clip the content. so, it's not the feasible solution here. In my opinion, resizing and aligning the component is a solution. But you can work as per your insights. @chicken-biryani would be able to assign you.

**Comment by Timonwa** [comment]
Hi @chicken-biryani , the pull request for this issue has been merged but this issue is still open. I think it should be closed
