### ISSUE TITLE
Bug: There is a difference in hover effects of the button.

### ISSUE THREAD

**Issue by Janvi-Thakkar** [moja-global/FLINT-UI#238]
### Describe the bug.

There should be unified hover effects for buttons. But buttons of different pages are having different hover effects.

### Describe the steps to reproduce the behavior.

1) Open the Flint-UI homepage.
2) Hover on explore button and see the effect.
3) Explore the RothC/ GCBM page.
4) Check the hover effects of configuration buttons.

### Expected behavior.

The explore button is having hover effect matching the theme. Other buttons should have the same hover effects.

### Screenshots.

![image](https://user-images.githubusercontent.com/55620053/163649159-137bc7b8-b696-4f49-91d0-ca4309dfeec3.png)
![image](https://user-images.githubusercontent.com/55620053/163649175-9b92878d-cbf2-4d8a-b34e-939c7a0db3ef.png)

### Operating Environment

Windows 10 - Chrome browser

**Comment by tewarig** [comment]
can I work on this issue?

**Comment by tewarig** [comment]
also one thing I am new here can you provide a link to RothC/ GCBM page

**Comment by Janvi-Thakkar** [comment]
@tewarig Welcome to Moja Global! You can click on the explore button given below RothC/ GCBM as shown in the picture to reach RothC/ GCBM page.

**Comment by void-hr** [comment]
Can you assign me this issue?

**Comment by Janvi-Thakkar** [comment]
> Can you assign me this issue?

@chicken-biryani

**Comment by chicken-biryani** [comment]
@Janvi-Thakkar since @tewarig commented first maybe he can take it up?

**Comment by Janvi-Thakkar** [comment]
> @Janvi-Thakkar since @tewarig commented first maybe he can take it up?

@chicken-biryani, I thought he is working on another one right now. I don't know what is preferable to do in such a case.😅

**Comment by void-hr** [comment]
@chicken-biryani  @Janvi-Thakkar No problem, @tewarig in case you haven't started yet please allow me to close this issue as I have been working for a while on this issue.

**Comment by chicken-biryani** [comment]
@void-hr if you've already worked on it I think you should continue and close this one.

Hope that's okay @tewarig?

**Comment by tewarig** [comment]
yes that is okay

**Comment by void-hr** [comment]
[Fix: difference in hover effects of button ](https://github.com/moja-global/FLINT-UI/pull/240)
