### ISSUE TITLE
Reference Vue 2 style guide in README 

### ISSUE THREAD

**Issue by aornugent** [moja-global/FLINT-UI#24]
The Vue docs are amazing. Let's make sure our UI developers know we follow them by adding a section to our README on coding style and providing a link:

~https://v3.vuejs.org/style-guide/~
 
EDIT: see comment from @waridrox

**Comment by waridrox** [comment]
We can look into https://vuejs.org/v2/style-guide/ now, since we are migrating back to Vue 2.
