### ISSUE TITLE
Refactor: Update Button Component with Ant Design

### ISSUE THREAD

**Issue by sohamsshah** [moja-global/FLINT-UI#243]
### Is your feature request related to a problem? Please describe.

Currently at multiple places in codebase, `Button` is used (not necessarily in component form).

In the [`/components/Button/Button.vue`](https://github.com/moja-global/FLINT-UI/blob/master/flint.ui/src/components/Button/Button.vue) one can find implementation of Button.

Since our project is actively Migrating to Ant Design, we shall consider refactoring it.

### Describe the solution you'd like.

- Refactor present Button component with Ant Design Button (with corresponding props based on our design like for example default width, height, color, hover states)
- Add Stories for the Component

**Comment by Iheanacho-ai** [comment]
can i take this issue up

**Comment by chicken-biryani** [comment]
@YashKandalkar is this issue still valid to be worked upon?
