### ISSUE TITLE
Refactor: Update `DatePickerPoint.vue` with Ant Design

### ISSUE THREAD

**Issue by sohamsshah** [moja-global/FLINT-UI#244]
### Is your feature request related to a problem? Please describe.

Currently our Point DatePicker Component is built with pure CSS implementation. 
One can check out `DatePicker.vue` component where Ant Design Implementation is present.

This component is used in [`ConfigurationsPoint.vue`](flint.ui\src\views\flint\ConfigurationsPoint.vue) file.

Reason for having separate DatePickers for each Configuration is that in future we might need customization, instead of prop-based development, separate component module for each would help us make is flexible.

### Describe the solution you'd like.

Refactor `ConfigurationsPoint.vue` file to have Ant Design Date Picker. Implementation can be discussed and brainstormed upon.

**Comment by Timonwa** [comment]
Good day @sohamsshah, can I work on this issue?
