### ISSUE TITLE
Refactor: Update `DatePickerRothC.vue` with Ant Design

### ISSUE THREAD

**Issue by sohamsshah** [moja-global/FLINT-UI#245]
### Is your feature request related to a problem? Please describe.

Currently our RothC DatePicker Component is built with pure CSS implementation. 
One can check out `DatePicker.vue` component where Ant Design Implementation is present.

This component is used in [`ConfigurationsRothC.vue`](flint.ui\src\views\flint\ConfigurationsRothC.vue) file.

Reason for having separate DatePickers for each Configuration is that in future we might need customization, instead of prop-based development, separate component module for each would help us make is flexible.

### Describe the solution you'd like.

Refactor `ConfigurationsRothC.vue` with latest Ant Design implementation like in `DatePicker/DatepIcker.vue` component.

**Comment by Timonwa** [comment]
Good day, can I work on this issue?

**Comment by padmajabhol** [comment]
> Good day, can I work on this issue?

Sure, all the best!
