### ISSUE TITLE
UI Update: RothC Parameter Configuration Page Redesign + Refactor

### ISSUE THREAD

**Issue by sohamsshah** [moja-global/FLINT-UI#246]
### Is your feature request related to a problem? Please describe.

Based on the new design:
![image](https://user-images.githubusercontent.com/47717492/163766510-e1f67fe4-6b57-4ad5-9a90-df4271ab217c.png)

All of the parameter configuration in the present implementation is in different routes. We need a single page form to input and test out RothC configuration interface. This issue focuses on UI side, api integration can be done in further PRs.

This would required refactoring the following:
- Update Routes files and delete unused files/components
- Redesign the whole UI with Ant Design and built-components in the design system
- Check for input validations and form filling of multiple fields in the project
- Re-confirm the fields with the team
- Remove all the css/tailwind related dependencies
- Convert to a single page.

**Comment by YashKandalkar** [comment]
Hi @sohamsshah If you haven't started working yet, can I take this one? 
I was working on https://github.com/moja-global/FLINT-UI/issues/183 but Accordion doesn't require a new component, a-collapse can be directly used.
I'll just convert the RothC views to components and show them on the configurations/rothc route. Someone else can work on fixing the UI of the input fields, and the other things you mentioned like validation, etc. 

If you're already made some progress you can continue on this!

**Comment by sohamsshah** [comment]
Hi @YashKandalkar , you can work on this! 👍
