### ISSUE TITLE
Refactor: Update `TableRothC.vue` file to use Ant Design Tables

### ISSUE THREAD

**Issue by sohamsshah** [moja-global/FLINT-UI#247]
### Is your feature request related to a problem? Please describe.

Currently the [`TableRothC.vue`](flint.ui\src\views\flint\TableRothC.vue) file is implemented with raw CSS and doesn't fit with latest UI design.

We will be using the Table component at multiple places in configurations for data display of interfaces.

### Describe the solution you'd like.

Refactor the `TableRothC.vue` file by replacing the css with Table Ant Design component and complying with our Table Design.

### Additional context.

Refer: https://antdv.com/components/table/#Table

**Comment by SanjaySinghRajpoot** [comment]
I would like to work on this issue.

**Comment by sohamsshah** [comment]
Sure @SanjaySinghRajpoot!

**Comment by YashKandalkar** [comment]
@chicken-biryani this can be closed, a fix was merged in #276

**Comment by chicken-biryani** [comment]
@YashKandalkar feel free to close issues and/or merge PRs now that you're a member as well!

You may get nervous at first but then you get used to it.
