### ISSUE TITLE
Refactor: Update `TablePoint.vue` file to use Ant Design Tables

### ISSUE THREAD

**Issue by sohamsshah** [moja-global/FLINT-UI#248]
### Is your feature request related to a problem? Please describe.

Currently the [`TablePoint.vue`](flint.ui\src\views\flint\TablePoint.vue) file is implemented with raw CSS and doesn't fit with latest UI design.

We will be using the Table component at multiple places in configurations for data display of interfaces.

### Describe the solution you'd like.

Refactor the `TablePoint.vue` file by replacing the css with Table Ant Design component and complying with our Table Design.

### Additional context.

Refer: https://antdv.com/components/table/#Table

**Comment by Janvi-Thakkar** [comment]
@sohamsshah I would like to work on this!

**Comment by sohamsshah** [comment]
Sure @Janvi-Thakkar , please go ahead. Make sure to build taking reusability in mind too ✌

**Comment by Janvi-Thakkar** [comment]
> 



> Sure @Janvi-Thakkar , please go ahead. Make sure to build taking reusability in mind too ✌

Sure, Thank You!
