### ISSUE TITLE
Bug: Sliding one of the sliders is showing shaking effects on other

### ISSUE THREAD

**Issue by Janvi-Thakkar** [moja-global/FLINT-UI#265]
### Describe the bug.

When we slide any of the sliders on the point page it makes other sliders shake. This is happening because the span of indication number is expanding as the number is increasing the digits.

### Describe the steps to reproduce the behavior.

1. Go to the Flint-UI homepage.
2. Explore the Point page.
3. Slide any of the sliders and observe the behavior. 

### Operating Environment

Windows 10 - Chrome browser

**Comment by Janvi-Thakkar** [comment]
@chicken-biryani if someone shows willingness to take this up, please assign it to him/her else I would love to fix it:)

**Comment by Iheanacho-ai** [comment]
can i take this on please

**Comment by Janvi-Thakkar** [comment]
> can i take this on please

@chicken-biryani

**Comment by Janvi-Thakkar** [comment]
Hello @Iheanacho-ai, are you working on this? or else we can assign it to some other contributor.

**Comment by RamGoel** [comment]
Hello @Janvi-Thakkar, this issue has been solved in (#365).

**Comment by Janvi-Thakkar** [comment]
@RamGoel That's great! Once that PR gets merged, I would close this issue:)
