### ISSUE TITLE
Bug: Map on Point page is blending with the UI

### ISSUE THREAD

**Issue by Janvi-Thakkar** [moja-global/FLINT-UI#266]
### Describe the bug.

When we see the geographical representation using a map, the map is opening on the same screen and it is blending in with the UI. We can use Popup to show the map.

### Describe the steps to reproduce the behavior.

1. Go to the Flint-UI homepage.
2. Explore the Point page.
3. Click on the "Click here" link provided for the Map.
4. Observe the behavior.

### Expected behavior.

Popup would help to clearly represent the Map view.

### Screenshots.

![image](https://user-images.githubusercontent.com/55620053/167313603-05723250-32e7-40af-b3a7-5cbe56ddb19b.png)

### Operating Environment

Windows 10 - Chrome browser

**Comment by Janvi-Thakkar** [comment]
@chicken-biryani I would like to take this up!

**Comment by chicken-biryani** [comment]
@Janvi-Thakkar go ahead

**Comment by Timonwa** [comment]
Can i take is issue? @chicken-biryani

**Comment by chicken-biryani** [comment]
@Timonwa if @Janvi-Thakkar isn't currently working on it then definitely!

**Comment by Janvi-Thakkar** [comment]
> @Timonwa if @Janvi-Thakkar isn't currently working on it then definitely!
I did not work on this because from May 28th's meeting, Yash and I asked regarding this to Shubham and got to know that this was developed just as a demo of UI. The longitudes and latitudes are nowhere used in the application. Until then these things were not clear to anyone. Sorry, I should update the details here earlier but I couldn't. 

@chicken-biryani Should I enhance the UI in this case?

**Comment by chicken-biryani** [comment]
@Janvi-Thakkar 
I think you can.

However I would like to hear your and
@YashKandalkar 's opinion on the same as well.

As current mentees it's the best that you take ownership of the projects you're currently working on.

**Comment by YashKandalkar** [comment]
@Janvi-Thakkar Yeah, I don't think we need a Modal now. There is still a problem tho - the input dates should come behind the map (probably a z-index issue), we can make a PR for that and close this issue. 
![image](https://user-images.githubusercontent.com/35102959/174090253-f35edf87-94ad-4d50-a22a-7bc236d8b46a.png)

**Comment by Janvi-Thakkar** [comment]
@YashKandalkar @chicken-biryani I think what I can do for now is make a modal to enhance the UI and leave the functionalities as it is for now. Later on, whenever we start using these parameters in simulation, we can integrate the logic at that time. In this way, we would be at least able to make UI presentable!!

**Comment by YashKandalkar** [comment]
@Janvi-Thakkar Sounds good!

**Comment by Timonwa** [comment]
Hi @Janvi-Thakkar, have you created the modal yet for the map or what's the update on this issue?

**Comment by Janvi-Thakkar** [comment]
Hello @Timonwa, yes modal has been created in UI library project and now we are working on replacing ant-design-vue components of Flint.UI with UI library components. So this will be replaced soon:)

**Comment by Timonwa** [comment]
Ok. Thank you for the update. @Janvi-Thakkar

**Comment by Janvi-Thakkar** [comment]
@chicken-biryani @Timonwa @YashKandalkar I tried to use the modal I created in UI Library. Below is the raw work I could do just by importing the modal. However, we can surely work on the appearance further!
![image](https://user-images.githubusercontent.com/55620053/184732401-862b3dcd-4e50-48d7-a174-cc466d8f626e.png)

Please let me know your thoughts! if this looks okay, then I would raise the PR:)

**Comment by Timonwa** [comment]
It looks good to me @Janvi-Thakkar, I like it. But there isn't a close button for the modal.

**Comment by chicken-biryani** [comment]
Looks neat!

Great job @Janvi-Thakkar! I agree with @Timonwa about the closing part.

**Comment by Janvi-Thakkar** [comment]
@chicken-biryani @Timonwa, as a general modal property we would be able to close by clicking on the dark gray area of the screen! However, in the future, we are planning to provide the optional prop to add or remove the close button!

**Comment by chicken-biryani** [comment]
@Janvi-Thakkar 

I think it's good. Would be happy to hear @YashKandalkar 's opinion before proceeding.

**Comment by YashKandalkar** [comment]
@Janvi-Thakkar this looks great!
