### ISSUE TITLE
Documentation: Update Sphinx theme to furo

### ISSUE THREAD

**Issue by Namyalg** [moja-global/FLINT-UI#274]
### What is the current documentation state?

The documentation currently uses the `read-the-docs` theme.

### Why do you want to improve the statement?

The main documentation has been revamped, with a change in theme to `furo`. To maintain uniformity across all projects, the documentation requires a change in theme

**Comment by ayush78781** [comment]
Hey! @Namyalg @padmajabhol @HarshCasper I worked upon this issue and converted the doc theme of Flint.Cloud & Flint.UI to furo. Here are some of the screenshots attached. Please let me know if any edits required.
<img width="952" alt="image" src="https://user-images.githubusercontent.com/76848435/170545763-bd99cb39-9077-44fc-854e-b364785c99bb.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/76848435/170545931-633a6f95-e54a-4f9d-9cae-1172c97d99a3.png">
If everything thing is Ok. Please let me know I will raise an PR for it.

**Comment by Namyalg** [comment]
Looks good, go ahead and raise a PR
