### ISSUE TITLE
Documentation: The link to the documentations should be updated on the webpage.

### ISSUE THREAD

**Issue by Timonwa** [moja-global/FLINT-UI#284]
### What is the current documentation state?
On the flint UI app, the link to the documentation site takes the user to the old documentation.

### Why do you want to improve the statement?
Since we have new documentation, I feel the link on the navbar pointing to the documentation site should also be updated.

### Proposed Statement
the old link: https://docs.moja.global/projects/flint-ui/en/latest/
the new link: https://docs.moja.global/en/master/

**Comment by thisiskaransgit** [comment]
I would like to work on this issue :)

**Comment by Timonwa** [comment]
@thisiskaransgit No one is working on it yet. But let's confirm that the links are correct before you make the corrections.

@chicken-biryani @HarshCasper. Please can you confirm if the changes I suggested in this issue is needed so that @thisiskaransgit can work on it.

**Comment by chicken-biryani** [comment]
@Timonwa that is correct.

@thisiskaransgit please feel free to work on it. Sorry for not replying sooner.

**Comment by thisiskaransgit** [comment]
Hey @Timonwa @chicken-biryani kindly review the PR 😊
