### ISSUE TITLE
Bug: Stepper GCBM component Relative Position

### ISSUE THREAD

**Issue by SanjaySinghRajpoot** [moja-global/FLINT-UI#286]
### Describe the bug.

Stepper GCBM component has a relative position property. 

### Describe the steps to reproduce the behavior.

Compile flint-ui and head over to the GCBM page.

### Expected behavior.

The Stepper component should have a fixed position. This can be achieved by changing the `bottom-0` attribute. 

### Screenshots.
![Screenshot from 2022-05-31 13-25-21](https://user-images.githubusercontent.com/67458417/171123419-b47ca824-37c1-49ec-beaa-773736200cfa.png)

### Operating Environment

Ubuntu 20.04

**Comment by CrystalSage** [comment]
I can solve this if anyone's not working on it already.

**Comment by chicken-biryani** [comment]
@CrystalSage please gi ahead!
