### ISSUE TITLE
Refactor: Replace Toasts with Ant Design Notifications

### ISSUE THREAD

**Issue by CrystalSage** [moja-global/FLINT-UI#314]
### Is your feature request related to a problem? Please describe.

Currently, the default way of notifying users is through `Toast` interface, offered by [vue-toastification](https://github.com/Maronato/vue-toastification). The proposal, as discussed on Slack, is to use Ant Design's [Notifications](https://antdv.com/components/notification) instead.

This way, we can get rid of the `vue-toastification` dependency.

### Describe the solution you'd like.

Replace the calls to `toast` throughout the web application, while making sure we stick to the original messages, notification types and duration.

### Additional context.

![image](https://user-images.githubusercontent.com/51860725/174433253-66c650f5-a4c7-4025-bc25-298bd35fb1db.png)

**Comment by CrystalSage** [comment]
I can work on this. Can someone assign this to me? @chicken-biryani maybe? :)

**Comment by chicken-biryani** [comment]
@CrystalSage please go ahead.
