### ISSUE TITLE
CI: add feat/gcbm-simulation-simulator branch in main.yml

### ISSUE THREAD

**Issue by YashKandalkar** [moja-global/FLINT-UI#327]
### Problem
The CI workflow (build, lint, etc.) only runs on master. I think we should add the `feat/gcbm-simulation-simulator` branch as it helps when PRs are created on that branch.

### Expected solution
Add `feat/gcbm-simulation-simulator` in [main.yml](https://github.com/moja-global/FLINT-UI/blob/8ff9d49b51c28c5b08a620a699e7d05301fe3985/.github/workflows/main.yml#L6)

**Comment by FrozenSamurai** [comment]
Please assign this issue to me.
