### ISSUE TITLE
migration: migrate ConfigurationsPoint to Vue 3 (Composition API)

### ISSUE THREAD

**Issue by YashKandalkar** [moja-global/FLINT-UI#333]
Migrate the [ConfigurationsPoint file](https://github.com/moja-global/FLINT-UI/blob/master/flint.ui/src/views/flint/ConfigurationsPoint.vue) in src/views/flint/ to use CompositionAPI (check out [this](https://github.com/moja-global/FLINT-UI/pull/311) PR by @Palaksharma23, or any other migration PR for reference.).

If you have any questions or need help please reach out to me (or any other community member) here or on Slack.

**Comment by CrystalSage** [comment]
I think I can solve this.
