### ISSUE TITLE
migration: migrate Table.vue to Vue 3 (Composition API) 

### ISSUE THREAD

**Issue by YashKandalkar** [moja-global/FLINT-UI#334]
- Migrate the [Table.vue file](https://github.com/moja-global/FLINT-UI/blob/master/flint.ui/src/views/flint/Table.vue) in src/views/flint/ to use CompositionAPI (check out https://github.com/moja-global/FLINT-UI/pull/311 PR by @Palaksharma23, or any other migration PR for reference.).
- Rename Table.vue to PointOutputTable.vue to make the name more descriptive.

If you have any questions or need help please reach out to me (or any other community member) here or on Slack.

**Comment by disha1202** [comment]
Hi @YashKandalkar,
I would like to work on this issue.
Can you please assign it to me.
