### ISSUE TITLE
migration: migrate PointOuterTable to Vue 3 (Composition API) 

### ISSUE THREAD

**Issue by YashKandalkar** [moja-global/FLINT-UI#335]
- Migrate the [PointOuterTable file](https://github.com/moja-global/FLINT-UI/blob/master/flint.ui/src/views/flint/PointOuterTable.vue) in src/views/flint/ to use CompositionAPI (check out https://github.com/moja-global/FLINT-UI/pull/311 PR by @Palaksharma23, or any other migration PR for reference.).
- Rename PointOuterTable to PointOutputContainer to make the name more descriptive

If you have any questions or need help please reach out to me (or any other community member) here or on Slack.

**Comment by Crystalsage** [comment]
I can work on this.

**Comment by chicken-biryani** [comment]
@Crystalsage go ahead.
