### ISSUE TITLE
migration: migrate RothCOutput.vue to Vue 3 (Composition API)

### ISSUE THREAD

**Issue by YashKandalkar** [moja-global/FLINT-UI#338]
- Migrate the [RothCOutput.vue file](https://github.com/moja-global/FLINT-UI/blob/master/flint.ui/src/views/flint/RothCOutput.vue) in src/views/flint/ to use CompositionAPI (check out https://github.com/moja-global/FLINT-UI/pull/311 PR by @Palaksharma23, or any other migration PR for reference.).
- Rename RothCOutput.vue to RothCOutputGraph.vue to make the name more descriptive.

If you have any questions or need help please reach out to me (or any other community member) here or on Slack.

**Comment by bhavyastar** [comment]
I would like to work on this issue. Would you please assign me? @YashKandalkar

**Comment by chicken-biryani** [comment]
@bhavyastar please go ahead.

**Comment by legendarykamal** [comment]
Hey @YashKandalkar @chicken-biryani since this issue had no response for more than a month, I have went ahead and completed it :+1:

**Comment by chicken-biryani** [comment]
Hey @legendarykamal thanks!
@YashKandalkar can you please take a look?
