### ISSUE TITLE
Bug: Alignment and style changes in footer

### ISSUE THREAD

**Issue by ItsRoy69** [moja-global/FLINT-UI#368]
### Describe the bug.

When the website is viewed in 414x896 there is some allignment issues in the "site links" and thus is hurting the eyes.

### Describe the steps to reproduce the behavior.

- Go to the link https://flint-ui.vercel.app/
- Resize the window to 414x896 and the button will split to multiple lines

### Expected behavior.

The "Site Links" and "Follow Us On" needs to be aligned or it can be used one after the other when the screensize is less than 400

### Screenshots.

![2022-08-25](https://user-images.githubusercontent.com/78967360/186575363-fc4ec4b4-8c78-46e3-adc4-5d9afc99ad46.png)

### Operating Environment

Windows 10 | Chrome Browser

**Comment by chicken-biryani** [comment]
Hey, @ItsRoy69 thanks for opening this issue.
Would you like to work on it?

**Comment by ItsRoy69** [comment]
For sure

**Comment by rahulsh18** [comment]
is this still being worked on?

**Comment by ItsRoy69** [comment]
I've been busy lately.. 🥲sorry .... I don't want to hold it more time... And almost forgot about this.. you can work

**Comment by Janvi-Thakkar** [comment]
@rahulsh18, Sorry but the footer has been replaced with UI-Library's footer recently. so this issue is no more in the scope!
