### ISSUE TITLE
Bug: Stepper overlapping on footer in mobile view

### ISSUE THREAD

**Issue by abhilipsasahoo03** [moja-global/FLINT-UI#374]
### Describe the bug.

The Run | Status | Download stepper in GCBM Explore section overlaps on the footer in mobile view. 

### Describe the steps to reproduce the behavior.

1. Go to https://flint-ui.vercel.app/gcbm/dashboard or https://flint-ui.vercel.app/gcbm/upload or https://flint-ui.vercel.app/gcbm/run

2. Switch to mobile view or resize the window to 414×896 and the stepper will overlap the footer. 

### Expected behavior.

The overlapping of stepper and footer should not happen and there should be some gap when in mobile view. 

### Screenshots.

![Screenshot_2022-09-07-08-57-12-093_com android chrome](https://user-images.githubusercontent.com/80174214/188785753-97feddca-d01f-4b08-9ccb-e6c2b621f207.jpg)

### Operating Environment

OS: Android | Browser: Chrome

**Comment by abhilipsasahoo03** [comment]
Hi @chicken-biryani can you assign me this issue, please?

**Comment by chicken-biryani** [comment]
@abhilipsasahoo03 please go ahead and work on it

**Comment by abhilipsasahoo03** [comment]
@chicken-biryani I think this issue can be closed since the new UI has been introduced and we can focus on issue #385
