### ISSUE TITLE
Bug: Non Alignment of text with the accociated image

### ISSUE THREAD

**Issue by legendarykamal** [moja-global/FLINT-UI#376]
### Describe the bug.
Space present , see the vertical alignment.

![image](https://user-images.githubusercontent.com/95926324/188913662-47265ee0-fc98-4e78-8fbd-77f390212b56.png)

![image](https://user-images.githubusercontent.com/95926324/188914282-d21fe2d6-fa23-43da-8bf8-d33301a6ddfc.png)

### Describe the steps to reproduce the behavior.

Go to the landing page

### Expected behavior.

The text should be properly aligned with the images

### Operating Environment

Any

**Comment by Shruti799** [comment]
Please assign this issue to me.

**Comment by chicken-biryani** [comment]
@Shruti799 will you be okay with taking up an issue @Crystalsage has created?

**Comment by Shruti799** [comment]
@chicken-biryani  Yeah, I would be okay with taking up this issue but I need some time as when I talked to @Crystalsage , he told me that I can't do/fix much with vanilla JS and need to know Vue which I have already started to learn. Very soon, I will be in a good position to tackle the issues.

**Comment by chicken-biryani** [comment]
@Shruti799 hope that you stick around!

**Comment by remote007** [comment]
Hey , if this issue is still available can I work on it ?

**Comment by Shruti799** [comment]
I am working on this issue.

**Comment by chicken-biryani** [comment]
@ktsrivastava29 @Shruti799 it's an invalid issue since this is not of the same codebase.
