### ISSUE TITLE
Feature Request: Replace current accordion component with UI-library's accordion component

### ISSUE THREAD

**Issue by Janvi-Thakkar** [moja-global/FLINT-UI#384]
### Additional context.

The current accordion can be found at: https://flint-ui.vercel.app/flint/configurations/rothc
Ui-library accordion reference link: https://moja-global-ui-library.vercel.app/?path=/story/components-accordion--primary
npm-package of UI-Library: https://www.npmjs.com/package/@moja-global/mojaglobal-ui

**Comment by thisiskaransgit** [comment]
I'd like to work on this issue

**Comment by Janvi-Thakkar** [comment]
@thisiskaransgit sure!
