### ISSUE TITLE
Feature Request: Replace range sliders of FLINT.UI with UI-library's slider component

### ISSUE THREAD

**Issue by Janvi-Thakkar** [moja-global/FLINT-UI#386]
### Additional context.

current slider link: https://flint-ui.vercel.app/flint/configurations/point
reference for UI-library sliders: https://moja-global-ui-library.vercel.app/?path=/story/components-slider--primary

**Comment by padmajabhol** [comment]
Hi @Janvi-Thakkar , can you please mark this issues and the others as OSD?

**Comment by chicken-biryani** [comment]
Hey @padmajabhol can you create the label and add it to the issues?

**Comment by Shruti799** [comment]
Is this issue still there? Can I work on it?

**Comment by khushbooag4** [comment]
I started working on this. Can you please assign this to me @Janvi-Thakkar @padmajabhol
