### ISSUE TITLE
Bug: RothC page crashes if table is displayed before simulation finishes

### ISSUE THREAD

**Issue by Crystalsage** [moja-global/FLINT-UI#387]
### Describe the bug.

When we go to `/flint/configurations/rothc` and click `Run` quickly followed by `Point Output Table` button , the whole thing crashes without any warnings or indicators. We would like to handle this more gracefully.

Refer to bug report #369. The behavior is pretty much the same including the stack trace.

### Describe the steps to reproduce the behavior.

1. Head over to `/flint/configurations/rothc`.
2. Click Run.
3. Immediately click `Point Output Table`.

### Expected behavior.

Handle this more gracefully and display an error notification if the simulation hasn't finished yet.

### Operating Environment

Arch Linux 5.18, Firefox, Ran locally with API deployed on azurewebsites.

**Comment by Crystalsage** [comment]
I'll take this up myself.

**Comment by Bhawna1203** [comment]
Hola @Palaksharma23 
I am working in this issue :)

**Comment by Palaksharma23** [comment]
Sure, go ahead :)

**Comment by Bhawna1203** [comment]
Hii @Crystalsage is this issue solved?
When I run it in my local system it is not showing me any crash if the table is displayed before the simulation finishes

**Comment by Crystalsage** [comment]
Hi @Bhawna1203. Sorry for the late reply, but yes the bug still exists. I was able to reproduce it without connecting to the actual FLINT API. 

Here's how I reproduced it:

1. Run the FLINT-UI on localhost.
2. Visit `/flint/configurations/rothc`
3. Click the `Run` button.
4. Click the `Show Output` button.
5. Check the console. The following stack trace was present.

```
Uncaught TypeError: (intermediate value).split is not a function
    parse_RothC_results rothc.js:529
    wrappedActionHandler vuex.esm-browser.js:305
    dispatch vuex.esm-browser.js:1031
    boundDispatch vuex.esm-browser.js:914
    showRothCOutputContainer ConfigurationsRothC.vue:164
    0 ConfigurationsRothC.vue:66
```

**Comment by Bhawna1203** [comment]
Okk Awesome Got it, I am working on solving this issues.
Thanks for letting me know this
