### ISSUE TITLE
[OSD] Bug: Incorrect hyperlinks in the footer

### ISSUE THREAD

**Issue by Crystalsage** [moja-global/FLINT-UI#389]
### Describe the bug.

Currently, we have some social media icons in the footer:
![image](https://user-images.githubusercontent.com/51860725/190561271-b90c4327-1265-4635-94ea-1a4d75f3a2f1.png)

Unfortunately, the hyperlinks for Twitter and Youtube have been interchanged. 

### Describe the steps to reproduce the behavior.

1. Scroll down to the footer.
2. Click on Twitter icon - it should lead you to Youtube, and vice versa.

### Expected behavior.

Fix this behaviour by swapping the hyperlinks that the icons point to.

### Operating Environment

Arch Linux, Firefox browser, API deployed on Azurewebsites, Latest commit

**Comment by rahulsh18** [comment]
i'd like to take this up

**Comment by chicken-biryani** [comment]
@rahulsh18 I think it'd be better to - complete the issues already taken up before taking up new ones.

**Comment by rahulsh18** [comment]
got it, apologies @chicken-biryani

**Comment by abhilipsasahoo03** [comment]
Hi @chicken-biryani @Crystalsage can I work on this?

**Comment by chicken-biryani** [comment]
@abhilipsasahoo03 yes!
