### ISSUE TITLE
Feature Request: Replace current card component with UI-library's card component 

### ISSUE THREAD

**Issue by Crystalsage** [moja-global/FLINT-UI#391]
### Additional context.

The current Card component can be found at: https://flint-ui.vercel.app

![image](https://user-images.githubusercontent.com/51860725/190562400-2c267d02-74c0-42d2-b5b8-2fb0f5d0ac00.png)

UI-library card reference link: https://moja-global-ui-library.vercel.app/?path=/story/components-card--normal
npm-package of UI-Library: https://www.npmjs.com/package/@moja-global/mojaglobal-ui

**Comment by rahulsh18** [comment]
hi @Crystalsage @padmajabhol i'd like to take this up

**Comment by Crystalsage** [comment]
Sure @rahulsh18 . Go ahead! :)

**Comment by Janvi-Thakkar** [comment]
Hello @rahulsh18, any updates on this issue?

**Comment by abhilipsasahoo03** [comment]
Hi @Janvi-Thakkar @chicken-biryani if this issue isn't currently being worked upon, can I take this up? Kindly let me know.

**Comment by chicken-biryani** [comment]
Hey @abhilipsasahoo03 please do

**Comment by abhilipsasahoo03** [comment]
> Hey @abhilipsasahoo03 please do

Sure thank you! @chicken-biryani
