### ISSUE TITLE
Feature Request: Replace current Modal component with UI-library's Modal component - ConfigurationsPoint

### ISSUE THREAD

**Issue by Crystalsage** [moja-global/FLINT-UI#392]
### Describe the solution you'd like.

Replace all of the Modal component instances in `ConfigurationsPoint.vue` only.

### Additional context.

The current Modal component can be found at: https://flint-ui.vercel.app/flint/configurations/point and other places throughout the project.

For Point simulation - run the simulation multiple times with the same pool values and it should trigger.

![image](https://user-images.githubusercontent.com/51860725/190562839-0dbfe204-7734-4985-b1c3-021c66aec9cb.png)

Current modal component reference: https://www.antdv.com/components/modal
UI-library modal reference link: https://moja-global-ui-library.vercel.app/?path=/story/components-modal--modal-card
npm-package of UI-Library: https://www.npmjs.com/package/@moja-global/mojaglobal-ui

**Comment by BboyAkers** [comment]
Hey! Going to work on this PR! Is that okay? 😸

**Comment by chicken-biryani** [comment]
@sambhavgupta0705 please do!

**Comment by Bhawna1203** [comment]
If no one working on this issue, Can I work @chicken-biryani ?

**Comment by sambhavgupta0705** [comment]
I was busy from couple of weeks so wasn't able to work on this,but will soon come back to this issue

> If no one working on this issue, Can I work @chicken-biryani ?

**Comment by chicken-biryani** [comment]
@sambhavgupta0705 if you think you'll take some more time let @Bhawna1203 take it up. We have loads of issues to pick up.

**Comment by sambhavgupta0705** [comment]
@chicken-biryani I have already started working on this.

**Comment by vedant-z** [comment]
@sambhavgupta0705 Are you still working on this issue? If not may I try this one @chicken-biryani ?

**Comment by thisiskaransgit** [comment]
Hey @sambhavgupta0705, it's been a month, are you still working on it, if you're not, @chicken-biryani, could you please assign this one to me?

**Comment by sambhavgupta0705** [comment]
@thisiskaransgit yeahh you can take this one,I tried solving it but wasn't able to do it.

**Comment by thisiskaransgit** [comment]
Hey @sambhavgupta0705, no worries, I was stuck too, so I asked for help,  also just wanted to remind you that you are assigned another, PR #388, let us know if you are working on it or not, and if you are stuck somewhere do share it slack, or in the community meeting.

**Comment by sambhavgupta0705** [comment]
yeahh @thisiskaransgit I will ask about it in next community meeting for sure
