### ISSUE TITLE
Feature Request: Replace current Notifications component with UI-library's Notifications component - CardInfoRun

### ISSUE THREAD

**Issue by Crystalsage** [moja-global/FLINT-UI#395]
### Describe the solution you'd like.

Replace all of the Notification component instances in `CardInfoRun.vue` only.

### Additional context.

The current Notification component can be found at: https://flint-ui.vercel.app/flint/configurations/point and other places throughout the project.

For Point simulation - run the simulation. A success notification should pop up.

![image](https://user-images.githubusercontent.com/51860725/190563883-82797ca9-7483-42bf-a2e0-2de6e8311f41.png)

Current notification component reference: https://www.antdv.com/components/notification
UI-library notification reference link: https://moja-global-ui-library.vercel.app/?path=/story/components-alert--solid-success
npm-package of UI-Library: https://www.npmjs.com/package/@moja-global/mojaglobal-ui

**Comment by abhilipsasahoo03** [comment]
@chicken-biryani @Crystalsage I'd like to work on this issue! Kindly assign.

**Comment by abhilipsasahoo03** [comment]
> Hey @abhilipsasahoo03 I know it's way past October... But would you still like to take this up?

Yeah totally. Sorry I was a bit inactive for few days. I'll work on it!

**Comment by chicken-biryani** [comment]
Thanks!

**Comment by sambhavgupta0705** [comment]
hi @chicken-biryani , I reviewed the previous PR of a contributor related to notification library to know more about UI library and after that I think I can easily solve this issue . 
Can I work on this one to get more comfortable with UI library.
