### ISSUE TITLE
[OSD] Feature Request: Replace current DatePicker component with UI-library's DatePicker component - DatePickerGCBM

### ISSUE THREAD

**Issue by Crystalsage** [moja-global/FLINT-UI#397]
### Describe the solution you'd like.

Replace all of the DatePicker component instances in `DatePickerGCBM.vue` only.

### Additional context.

The current Datepicker component can be found at: https://flint-ui.vercel.app/flint/configurations/point and other places throughout the project.

[![image](https://user-images.githubusercontent.com/51860725/190565742-ee72d489-b560-481b-b966-724138b4b7a9.png)

Current datepicker component reference: https://www.antdv.com/components/date-picker
UI-library notification reference link: https://moja-global-ui-library.vercel.app/?path=/story/components-datepicker--mandatory-prop
npm-package of UI-Library: https://www.npmjs.com/package/@moja-global/mojaglobal-ui

**Comment by abhilipsasahoo03** [comment]
Hi @Crystalsage I'd like to work on this issue!

**Comment by Crystalsage** [comment]
@abhilipsasahoo03 Sure! Go ahead please.

Also, make sure you don't have any outstanding issues before taking up new ones.

**Comment by abhilipsasahoo03** [comment]
Yes, I'll make sure!

**Comment by padmajabhol** [comment]
@abhilipsasahoo03 are you currently working ongoing issue?

**Comment by abhilipsasahoo03** [comment]
@padmajabhol yes I am, I'll create a PR by tonight.
