### ISSUE TITLE
Feature Request: Replace current DatePicker component with UI-library's DatePicker component - DatePickerPoint

### ISSUE THREAD

**Issue by Crystalsage** [moja-global/FLINT-UI#399]
### Describe the solution you'd like.

Replace all of the DatePicker component instances in `DatePickerPoint.vue` only.

### Additional context.

The current Datepicker component can be found at: https://flint-ui.vercel.app/flint/configurations/point and other places throughout the project.

[![image](https://user-images.githubusercontent.com/51860725/190565742-ee72d489-b560-481b-b966-724138b4b7a9.png)

Current datepicker component reference: https://www.antdv.com/components/date-picker
UI-library notification reference link: https://moja-global-ui-library.vercel.app/?path=/story/components-datepicker--mandatory-prop
npm-package of UI-Library: https://www.npmjs.com/package/@moja-global/mojaglobal-ui

**Comment by Crystalsage** [comment]
Hi @legendarykamal. Please consider finishing your PR #370 first.

**Comment by Vaani-pathariya** [comment]
Hello ! @Crystalsage , Can I take up this one ??

**Comment by chicken-biryani** [comment]
@Vaani-pathariya please do!

**Comment by suhaasya** [comment]
@Vaani-pathariya are you working on this?

**Comment by Vaani-pathariya** [comment]
yes i am

**Comment by Vaani-pathariya** [comment]
No , not currently , you may work on it @suhaasya

**Comment by suhaasya** [comment]
@Vaani-pathariya okay then, i will start work on it.

**Comment by suhaasya** [comment]
hey @Crystalsage and @chicken-biryani  this issue is already resolved you can close the issue.
