### ISSUE TITLE
Add a table component

### ISSUE THREAD

**Issue by aornugent** [moja-global/FLINT-UI#4]
The RothC example takes in JSON arrays as config. It'd be nice to display these in a table. Here are some examples:

https://tailwindcss.com/docs/table-layout
https://vuematerial.io/components/table

**Comment by shubhamkarande13** [comment]
@aornugent Is it okay if we just display the `response` itself in a table format?

**Comment by aornugent** [comment]
That sounds like a good place to start! Ultimately we will want to be consistent with how we display time series data throughout the client.

**Comment by shubhamkarande13** [comment]
Fixed via #56.
