### ISSUE TITLE
Feature Request: Replace current Notifications component with UI-library's Notifications component - DatePickerRothC

### ISSUE THREAD

**Issue by Crystalsage** [moja-global/FLINT-UI#400]
### Describe the solution you'd like.

Replace all of the Notification component instances in `DatePickerRothC.vue` only.

### Additional context.

The current Notification component can be found at: https://flint-ui.vercel.app/flint/configurations/point and other places throughout the project.

For Point simulation - run the simulation. A success notification should pop up.

![image](https://user-images.githubusercontent.com/51860725/190563883-82797ca9-7483-42bf-a2e0-2de6e8311f41.png)

Current notification component reference: https://www.antdv.com/components/notification
UI-library notification reference link: https://moja-global-ui-library.vercel.app/?path=/story/components-alert--solid-success
npm-package of UI-Library: https://www.npmjs.com/package/@moja-global/mojaglobal-ui

**Comment by Adityasaini10012001** [comment]
please assign this to me

**Comment by suhaasya** [comment]
@chicken-biryani @Crystalsage i would like to work on this.

**Comment by chicken-biryani** [comment]
@suhaasya please do!

**Comment by suhaasya** [comment]
@chicken-biryani @Crystalsage can you please review the PR?
