### ISSUE TITLE
Documentation: Add min node version for local setup 

### ISSUE THREAD

**Issue by meenakshi-dhanani** [moja-global/FLINT-UI#406]
### What is the current documentation state?

In [Development Notes](https://github.com/moja-global/FLINT-UI/blob/master/docs/DevelopmentGuide/DevelopmentNotes.rst), the local setup for the UI doesn't mention the min. node version. 

### Where is this stated?

https://github.com/moja-global/FLINT-UI/blob/master/docs/DevelopmentGuide/DevelopmentNotes.rst

### Why do you want to improve the statement?

Faster and easier local setup

### Proposed Statement

Mention the min. node version required

**Comment by abhilipsasahoo03** [comment]
Hi @chicken-biryani I'd like to work on this!
