### ISSUE TITLE
Bug : Accordion Overlapping 

### ISSUE THREAD

**Issue by thisiskaransgit** [moja-global/FLINT-UI#409]
### Describe the bug.

While fixing issue #384, I found that the last component's header overlaps the content of the above component's content when the latter is expanded.

### Describe the steps to reproduce the behavior.

1. Go to https://flint-ui.vercel.app/flint/configurations/rothc
2. Expand the second to last card "**Initial conditions of the Soil (initSoil)**"

### Expected behavior.

The cards should have enough space to display the information clearly.

### Screenshots.

![Screenshot from 2022-09-24 01-22-54](https://user-images.githubusercontent.com/92504666/192049519-fef5c595-aec1-448b-a3b9-9e7a11eea4c0.png)
![Screenshot from 2022-09-24 01-25-01](https://user-images.githubusercontent.com/92504666/192049540-0cf806c3-4444-4c48-8f0f-33bfe998dcaf.png)

### Operating Environment

OS:Ubuntu-22.04  Browser: Chromium

**Comment by thisiskaransgit** [comment]
Can I work on this one?

**Comment by Crystalsage** [comment]
This is possibly a duplicate of #390. In that case - please close this issue. Once you make a PR with the bugfix, mention #390. 

Thanks @thisiskaransgit! :)

**Comment by thisiskaransgit** [comment]
Sorry, I overlooked the listed issues. I have solved the issue and will create a PR mentioning #390
