### ISSUE TITLE
Bug: Header of RothC configuration section is not visible in mobile view

### ISSUE THREAD

**Issue by sambhavgupta0705** [moja-global/FLINT-UI#453]
### Describe the bug.

The header is not visible in mobile view.Basically it is getting covered by the navbar.

### Describe the steps to reproduce the behavior.

- Go to [configurations/rothc](https://flint-ui.vercel.app/flint/configurations/rothc)
- Open the site in mobile view and scroll to the top.

### Expected behavior.

The header should be visible and must be beneath navbar

### Screenshots.

![image](https://user-images.githubusercontent.com/81870866/219605212-522352bc-0b95-4af2-94ee-3513f7b6b5ed.png)

### Operating Environment

Ubuntu 22.04

**Comment by ConnectBhawna** [comment]
@Janvi-Thakkar @Palaksharma23 Can you please assign me this issue? 
I would love to work on this issue
Thank you

**Comment by Palaksharma23** [comment]
Sure, go ahead :) @connectBhawna

**Comment by Palaksharma23** [comment]
Sure, go ahead :) @connectBhawna
