### ISSUE TITLE
Storybook not working

### ISSUE THREAD

**Issue by shubhamkarande13** [moja-global/FLINT-UI#48]
**Describe the bug**
Storybook doesn't work. Also I don't know why is it in the default docker compose file. We should have a different docker compose file for running Storybook with the FLINT UI.

**To Reproduce**

Run `docker-compose up --build` from the FLINT-UI directory.

**Expected behavior**
Storybook should work.

**Screenshots**
Please check the comments. 
CC: @waridrox

**Comment by waridrox** [comment]
Hi @iamrajiv, I think the storybook fails at the `docker-compose up --build cmd`. The build cmd itself takes a lot of time to build the container, (most of the time going into building storybook)

![image](https://user-images.githubusercontent.com/58583793/129427102-8104cb6b-151b-4322-82b3-8496ff63d9f5.png)

**Comment by aornugent** [comment]
Thanks for raising this issue! 

I don't think we need a separate compose file, but just comment it out for now. This should be a 30sec PR (one change, one commit) so I absolutely recommend fixing issues with the developer experience.

@waridrox can you please do this? Remember to do it off master so that you don't bring any unintended changes from your other branches.

**Comment by shubhamkarande13** [comment]
Umm, @aornugent I think normal users won't need to use Storybook? So maybe we could have a different docker compose file specifically for developers?

**Comment by aornugent** [comment]
I strongly disagree with having two compose files. It is confusing to users and developers.

Let's comment it out until the feature is working correctly. Later we can document our choice to include Storybook and give users the option to enable or disable.

**Comment by waridrox** [comment]
The storybook could make more sense once it has been deployed somewhere to like gh-pages, and maybe `docker-compose` could serve storybook for development purposes...
