### ISSUE TITLE
CI build failing 

### ISSUE THREAD

**Issue by aornugent** [moja-global/FLINT-UI#49]
#44 uncovered an dependency incompatibility that was not resolved before merge, meaning our CI pipeline does not currently build.

@shubhamkarande13 - can you please post the error message here? Let's try to find a solution!

**Comment by shubhamkarande13** [comment]
[Build failed.](https://github.com/moja-global/FLINT-UI/runs/3313912666)

**Comment by aornugent** [comment]
@waridrox can you please explain how you resolved this so that @shubhamkarande13 knows how to fix it next time?

**Comment by waridrox** [comment]
The issue I think lies with the `package-lock.json` file, we added that in `.gitignore` which meant there was no way to update the file. Removing that and committing the new `package-lock.json` file resolved this at #50
