### ISSUE TITLE
Use a stepper to simplify multi-step config

### ISSUE THREAD

**Issue by aornugent** [moja-global/FLINT-UI#5]
Most configurations will have multiple steps. In RothC this might mean inputting multiple JSON arrays, for GCBM it could be uploading different types of files (input databases, disturbance histories).

We can create short workflows using: https://vuematerial.io/components/steppers

See also the integration with Vue Router to maintain browser history nicely,

**Comment by shubhamkarande13** [comment]
@waridrox Can we close this issue?
