### ISSUE TITLE
Implement file upload component

### ISSUE THREAD

**Issue by aornugent** [moja-global/FLINT-UI#6]
We need to upload multiple files to the FLINT endpoints. Vue Material has a nice file upload component: https://vuematerial.io/components/file/

**Comment by shubhamkarande13** [comment]
I tried their demo but it does not seem like it supports drag and drop functionality, as suggested by @mfellows.

We found [vue-upload-component](https://github.com/lian-yue/vue-upload-component) and @waridrox has managed to import it, although some changes are required.

![image](https://user-images.githubusercontent.com/13800316/127243648-88bb11f7-ee0f-4777-b2d1-0905138206e2.png)

**Comment by aornugent** [comment]
Drag and drop isn't critical for now, but great if you have found a solution. Otherwise fall back to Vue Material and we can use the file browser instead.
