### ISSUE TITLE
Uploading unsupported mime type files from the browser

### ISSUE THREAD

**Issue by waridrox** [moja-global/FLINT-UI#61]
The params for uploading file types in the GCBM runs requires specific file types to be uploaded that are unsupported via the MIME standards in the browser. Some of these are `.db`, `.cfg`, `.conf` etc. Here's the list for the supported file types in the browser - https://www.iana.org/assignments/media-types/media-types.xhtml

This is how the file types are getting referenced in the file uploader -
```javascript
accepted-file-types="image/tiff, image/x-tiff, application/json, application/x-geotiff, application/gml+xml, application/x-wms, text/xml, "

```

The closest thing that may be possible now is the `.zip` file type which would be sent to the upload route and unzipped there...

CC: @aornugent @shubhamkarande13 @HarshCasper

**Comment by Tlazypanda** [comment]
Hey @waridrox @shubhamkarande13 can you share the entire api call that is being made? The upload requests are made with `Content-Type: multipart/form-data` so can you share the exact error log for the same? Thanks :v:

**Comment by waridrox** [comment]
Hi @Tlazypanda, the api calls are yet to be made in the `multipart/form-data` part, but before that we would like the user to upload the dataset files as per their requirements from the web browser. Hence the file upload component needs a specific file type to accept the files from the browser...

https://user-images.githubusercontent.com/58583793/130262721-132ebe87-a90b-482f-bf60-0a80cbe28330.mov

**Comment by Tlazypanda** [comment]
Hey @waridrox I am not sure what change is required on the api end now because if I understand correctly this is on the UI level the file upload component right? If we finally make the api request to multipart/form-data this would be working then :v:

**Comment by waridrox** [comment]
Yes 💯, that would work on the request to multipart/form-data. It's the browser file upload functionality that needs to be tackled first.

**Comment by aornugent** [comment]
Oh that's disappointing! How about we proceed with a zip upload while we work towards a minimum viable product but leave this discussion open for further consideration?

This might mean users are not able to edit the config using the UI until we resolve this issue.

**Comment by shubhamkarande13** [comment]
@aornugent Don't worry I have found an alternative component that doesn't restrict uploads on file type or mime type. 
Tada 🎉! [Dropzone!](https://github.com/rowanwins/vue-dropzone)

![image](https://user-images.githubusercontent.com/13800316/130303097-0ebd0e83-f2e4-4861-aed8-a95e3ccf390d.png)

It looks a bit ugly but can I push the code to this branch till Warid fixes the design when he wakes up (it's 5 AM here)?

**Comment by shubhamkarande13** [comment]
@aornugent @waridrox @Tlazypanda 
Upload works!

![image](https://user-images.githubusercontent.com/13800316/130304014-0f0399f0-4bb3-42dd-89b3-f7c0508a967e.png)

Thank you Sneha for your insights! ✌😄

**Comment by waridrox** [comment]
Thanks for everyone's insights, the file upload component that was being used proved to be the limitation instead.

Closing this via #64
