### ISSUE TITLE
Use line graphs to summarise time-series config and results

### ISSUE THREAD

**Issue by aornugent** [moja-global/FLINT-UI#7]
Graphs are much easier quickly review than data tables. Taswira demonstrates this well with it's [change graph](https://github.com/moja-global/GCBM.Visualisation_Tool/blob/master/screenshot.png).

These ones look nice and they have a clear example of displaying local and API data: https://vue-chartjs.org/guide/#chart-with-api-data

**Comment by shubhamkarande13** [comment]
Sadly vue-chartjs does not support Vue 3, which is the version of Vue we are using.

For more info:
https://github.com/apertureless/vue-chartjs#compatibility

**Comment by shubhamkarande13** [comment]
[apexcharts](https://apexcharts.com/docs/vue-charts/) could be a good alternative with official Vue3 support. I tried setting up an example chart but it is giving me a blank page.

![image](https://user-images.githubusercontent.com/13800316/127243202-b5f75b28-7633-43b0-a9d1-ddc7a5ad4136.png)

@waridrox and I are still figuring this out.

**Comment by aornugent** [comment]
ApexCharts looks like a good alternative - there's also a Vue3 compatible rewrite of VueCharts here: https://github.com/victorgarciaesgi/vue-chart-3

**Comment by waridrox** [comment]
ApexCharts supports Vue 2 as well as Vue 3 so there shouldn't be any problem if we downgrade the app to Vue 2 - https://apexcharts.com/docs/vue-charts/

**Comment by aornugent** [comment]
Following the migration we can also evaluate vue-charts 🎯

**Comment by shubhamkarande13** [comment]
Reopening this issue as the graph support broke due to the state refactor.
