### ISSUE TITLE
Publishing Docker images to GitHub container registry using continuous integration (CI) workflow

### ISSUE THREAD

**Issue by iamrajiv** [moja-global/FLINT-UI#71]
## Description

As of now, moja global docker images are put in Docker Hub by different people with their accounts so it's hard to have control over that. Also, there are no Continuous integration workflows set up in the repository so the images are not able to update when there is a new release in the project.

To overcome this problem let's have a consistent platform to put our docker images. I would just let's publish the docker images to the GitHub container registry. Also, we will add Continuous integration workflows to make the docker images updated.

> GitHub container registry is a part of GitHub Packages. It is a software package hosting service that allows you to host your software packages privately or publicly and use packages as dependencies in your projects.

To automate the task we will need two Github Action i.e. `docker-image.yaml` which will build a docker image to deploy, run, or push to a registry, and `docker-publish.yaml` which will build, test, and push docker image to GitHub container registry.

These two actions will run whenever there is a push to the `main` or `master` branch or we can also set a cron job to run these two actions.

**Comment by aornugent** [comment]
Tagging @HarshCasper @Tonnix - this approach seems general and can be integrated across all repos.

@Tonnix - can you please review and see if this is compatible with your PR on FLINT.Docker? I'd love to get all moja global images consolidated and updated in one place.

**Comment by Tonnix** [comment]
Hi @aornugent, @iamrajiv, @HarshCasper  ,

Overall, I like the idea, and yes, it carries my PR a step further.

A single authoritative repository for FLINT Images Build Source Repository is something I've been rooting for for a while.
It will eliminate redundancies and ensure that the Docker images are up to speed with the current development.

What is not clear at this point (or I'm not seeing at this point) is:-

1) If consideration has been made to have the build scripts - at the source repository level - update the official FLINT images Repository centrally hosted at Dockerhub i.e.

a) FLINT Base Image currently at : https://hub.docker.com/r/mojaglobal/baseimage
b) FLINT image currently: https://hub.docker.com/r/mojaglobal/flint

2) If point 1 above holds true, what is the versioning strategy for the image builds?

3) If point 1 above holds true and there is a versioning strategy, what consideration has been made to notify interested parties (i.e. parties running official flint implementations) of image updates.

To illustrate with the SLEEK Implementation case:-

- The SLEEK implementation has its own Docker Image which uses FLINT as a base image: see https://hub.docker.com/r/mojaglobal/moja.sleek
- Having proprietary modules this image is updated privately, away from the official FLINT build processes
- So whenever FLINT images are updated, maintainers of the SLEEK Image need to be updated to update their images as well.

The same case will hold for other FLINT Implementations

**Comment by aornugent** [comment]
@iamrajiv - do you have any further proposals? I could create a DevOps team to any repos containing Dockerfiles if there's a solution to be implemented. It'll just need a design doc and execution.

**Comment by iamrajiv** [comment]
@aornugent I think this issue is almost solved like we are able to publish the images in the GitHub container registry. Only GCBM image is left but I think to build the image for GCBM we need GCBM files as of now we are using `tlazypanda/gcbm` image.

**Comment by iamrajiv** [comment]
@aornugent I think this issue is almost solved like we have published the images in the GitHub container registry [here](https://github.com/orgs/moja-global/packages). Only GCBM image is left but I think to build the image for GCBM we need GCBM files as of now we are using `tlazypanda/gcbm` image.

**Comment by iamrajiv** [comment]
@aornugent I think this issue is almost solved like we have published the images in the GitHub container registry [here](https://github.com/orgs/moja-global/packages). Only GCBM image is left but I think to build the image for GCBM we need GCBM files as of now we are using `tlazypanda/gcbm` image.
