### ISSUE TITLE
Documentation: Update Installation Doc on Sphinx

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/FLINT-UI#75]
### What is the current documentation state?

Currently, there is no installation documentation on the Sphinx website.

### Where is this stated?

We can have an `installation.rst` file and link it to the `index.rst` to have it centrally on the website.

### Proposed Statement

We can just copy the instructions on the README.md file and copy that to a Sphinx file.

**Comment by aornugent** [comment]
Hey @HarshCasper - there seems to be something wrong with this message:

> Hello there @{{ github.actor }} 👋

**Comment by iamrajiv** [comment]
@aornugent Above issue i.e. @{{ github.actor }} has been fixed in #77.
