### ISSUE TITLE
Put simulation location on a map

### ISSUE THREAD

**Issue by aornugent** [moja-global/FLINT-UI#8]
Most spatially explicit models (Chapman Richards, GCBM) have coordinates. It'd be nice to give users a sense of place when they're running their models. VueLayers looks like a nice framework for this feature.

The very simplest test we can try is to add a Latitude and Longitude to the Point example endpoint and let users choose where their simuation takes place: https://vuelayers.github.io/#/docs/component/point-geom

**Comment by aornugent** [comment]
@shubhamkarande13 pointed out that the Point endpoint does not currently have latitude and longitude, so this will need to be added to the Vuex store.

**Comment by shubhamkarande13** [comment]
I think this issue is fixed via #35.
@waridrox your thoughts?

**Comment by waridrox** [comment]
Yes I think this has been addressed but since there is no point coordinates for the simulation runs, we are just storing `lat` and `long` coordinates as states in the app.
