### ISSUE TITLE
Restructure the README.

### ISSUE THREAD

**Issue by chicken-biryani** [moja-global/FLINT-UI#82]
**To do:** Update the [README](https://github.com/moja-global/FLINT-UI/blob/master/README.md) file.

In order to work on this issue:

1) Claim this issue: Comment below to claim this issue.

2) You can go through this [tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) if you aren't familiar with working around with Github.

3) **Restructure the [README](https://github.com/moja-global/FLINT-UI/blob/master/README.md) file as follows:**

- Table of Contents:
- About Project.
- Built with.
- Getting started.
 	- Prerequisites.
 	- Installation.
- Developer notes.
- How to Get Involved?
- Contributors
- Maintainers Reviewers Ambassadors Coaches.
- License

You can use [this template](https://github.com/othneildrew/Best-README-Template#getting-started) for reference.

4) Commit your changes and create a Pull Request.

If you feel stuck or would like to ask questions/have a discussion you can reach out to us on [Slack](https://join.slack.com/t/mojaglobal/shared_invite/zt-o6ta1ug0-rVLjAo460~d7JbZ~HpFFtw) or comment your doubt under this issue itself.

**Comment by soil-droid** [comment]
can i work on this?

**Comment by raffaelecalza** [comment]
Hi 👋 , can I work on this for the hacktoberfest? Or is there someone already working on?

**Comment by chicken-biryani** [comment]
Hey, @soil-droid sure go ahead!

@raffaelecalza That was a really close call! But don't worry there are more issues coming up!

**Comment by chicken-biryani** [comment]
Hey, @raffaelecalza sure! Go ahead!

**Comment by raffaelecalza** [comment]
> Hey, @raffaelecalza sure! Go ahead!

Ok, I'll work on it tomorrow. Thank you

**Comment by raffaelecalza** [comment]
Hi @chicken-biryani , I'm working on the README. I've got one little question: should I change also the text or should I only move the text in the correct position following the structure you suggested?

**Comment by chicken-biryani** [comment]
Hey @raffaelecalza ,

For now just correct the position.

You could open a seperate Issue with proposed changes you'd like to see and After that a seperate pull request for the proposed changes. Does that sound okay?

**Comment by raffaelecalza** [comment]
Hi @chicken-biryani I've opened a PR (#85). Let me know if there is any problem
