### ISSUE TITLE
Improve application state management to handle multiple jobs

### ISSUE THREAD

**Issue by aornugent** [moja-global/FLINT-UI#9]
Currently application state is set in individual components, but this becomes tricky to manage when accessing data across multiple components (e.g. #5). 

Soon we will also be adding job management to the GCBM using the Create -> Upload -> Run -> Review workflow, where the configuration and outputs occur in different parts of our application.

Therefore we need an improved state management framework. I recommend Vuex but welcome other design considerations.
https://vuex.vuejs.org/guide/state.html#single-state-tree

**Comment by aornugent** [comment]
An additional design consideration is whether to add all endpoint specific state, mutations and actions to `store/index.js` or whether we can refactor this a more logical structure that either:
1. has one module per endpoint (e.g. `store/point.js`, `store/rothc.js`; or
2. has one module for each type (e.g. `actions.js`, `state.js`, `mutations.js`; or
3. both (e.g. `point/state.js`, `point/actions,js` , `point/mutations.js`, `rothc/state.js`, `rothc/actions.js`, `rothc/mutations.js`

I think I prefer option 3, but please discuss the merits and feasbility of each, or alternative designs.

**Comment by aornugent** [comment]
This is a particularly tidy looking design: https://www.smashingmagazine.com/2021/07/tools-practices-speed-up-vuejs-development-process/#organizing-modules

**Comment by waridrox** [comment]
With #35, the states have been refactored into Vuex modules. Info for the same can be found out here - https://vuex.vuejs.org/guide/modules.html

Thus now the directory structure for the states stored in the `store` folder becomes: 
```javascript
.
└── store
    ├── index.js
    └── modules
        ├── point.js
        ├── rothc.js
        └── vuelayers.js

```

where `index.js` is the parent file where we can import the desired modules from the modules folder and even share the states across different modules if the methods are declared inside the `index.js` file.
